// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device/device_variant_id.proto

package device

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Globally unique identifier.
type DeviceVariantId struct {
	// Required.
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceVariantId) Reset()         { *m = DeviceVariantId{} }
func (m *DeviceVariantId) String() string { return proto.CompactTextString(m) }
func (*DeviceVariantId) ProtoMessage()    {}
func (*DeviceVariantId) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d79d6802c0a98a4, []int{0}
}

func (m *DeviceVariantId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceVariantId.Unmarshal(m, b)
}
func (m *DeviceVariantId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceVariantId.Marshal(b, m, deterministic)
}
func (m *DeviceVariantId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceVariantId.Merge(m, src)
}
func (m *DeviceVariantId) XXX_Size() int {
	return xxx_messageInfo_DeviceVariantId.Size(m)
}
func (m *DeviceVariantId) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceVariantId.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceVariantId proto.InternalMessageInfo

func (m *DeviceVariantId) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceVariantId)(nil), "device.DeviceVariantId")
}

func init() { proto.RegisterFile("device/device_variant_id.proto", fileDescriptor_9d79d6802c0a98a4) }

var fileDescriptor_9d79d6802c0a98a4 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x49, 0x2d, 0xcb,
	0x4c, 0x4e, 0xd5, 0x87, 0x50, 0xf1, 0x65, 0x89, 0x45, 0x99, 0x89, 0x79, 0x25, 0xf1, 0x99, 0x29,
	0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x09, 0x25, 0x75, 0x2e, 0x7e, 0x17, 0x30,
	0x2b, 0x0c, 0xa2, 0xc2, 0x33, 0x45, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82,
	0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x71, 0x32, 0x8a, 0x32, 0x48, 0xcf, 0xd7, 0x4b, 0xce,
	0x28, 0xca, 0xcf, 0xcd, 0x2c, 0xcd, 0xd5, 0xcb, 0x2f, 0x4a, 0xd7, 0x87, 0x71, 0xf2, 0x8b, 0xf5,
	0x33, 0xf3, 0xd2, 0x8a, 0x12, 0xf5, 0xc1, 0x46, 0xeb, 0xa7, 0xe7, 0x43, 0x6d, 0x4d, 0x62, 0x03,
	0x0b, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x2f, 0xfe, 0x5d, 0x8d, 0x00, 0x00, 0x00,
}
