// Code generated by protoc-gen-go. DO NOT EDIT.
// source: device/device_brand_id.proto

package device

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Globally unique identifier.
type DeviceBrandId struct {
	// Required.
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceBrandId) Reset()         { *m = DeviceBrandId{} }
func (m *DeviceBrandId) String() string { return proto.CompactTextString(m) }
func (*DeviceBrandId) ProtoMessage()    {}
func (*DeviceBrandId) Descriptor() ([]byte, []int) {
	return fileDescriptor_d723777ad354ad74, []int{0}
}

func (m *DeviceBrandId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceBrandId.Unmarshal(m, b)
}
func (m *DeviceBrandId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceBrandId.Marshal(b, m, deterministic)
}
func (m *DeviceBrandId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceBrandId.Merge(m, src)
}
func (m *DeviceBrandId) XXX_Size() int {
	return xxx_messageInfo_DeviceBrandId.Size(m)
}
func (m *DeviceBrandId) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceBrandId.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceBrandId proto.InternalMessageInfo

func (m *DeviceBrandId) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceBrandId)(nil), "device.DeviceBrandId")
}

func init() { proto.RegisterFile("device/device_brand_id.proto", fileDescriptor_d723777ad354ad74) }

var fileDescriptor_d723777ad354ad74 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x49, 0x2d, 0xcb,
	0x4c, 0x4e, 0xd5, 0x87, 0x50, 0xf1, 0x49, 0x45, 0x89, 0x79, 0x29, 0xf1, 0x99, 0x29, 0x7a, 0x05,
	0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x61, 0x25, 0x55, 0x2e, 0x5e, 0x17, 0x30, 0xcb, 0x09,
	0x24, 0xef, 0x99, 0x22, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x2a, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x38, 0x19, 0x45, 0x19, 0xa4, 0xe7, 0xeb, 0x25, 0x67, 0x14, 0xe5,
	0xe7, 0x66, 0x96, 0xe6, 0xea, 0xe5, 0x17, 0xa5, 0xeb, 0xc3, 0x38, 0xf9, 0xc5, 0xfa, 0x99, 0x79,
	0x69, 0x45, 0x89, 0xfa, 0x60, 0x83, 0xf5, 0xd3, 0xf3, 0xa1, 0x36, 0x26, 0xb1, 0x81, 0x05, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x22, 0x7e, 0x38, 0x6a, 0x89, 0x00, 0x00, 0x00,
}
