// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/builder_config.proto

package chromiumos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Type of build.
type BuilderConfig_Id_Type int32

const (
	BuilderConfig_Id_TYPE_UNSPECIFIED BuilderConfig_Id_Type = 0
	// Commit queue build.
	BuilderConfig_Id_CQ BuilderConfig_Id_Type = 1
	// Postsubmit build.
	BuilderConfig_Id_POSTSUBMIT BuilderConfig_Id_Type = 2
)

var BuilderConfig_Id_Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "CQ",
	2: "POSTSUBMIT",
}

var BuilderConfig_Id_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"CQ":               1,
	"POSTSUBMIT":       2,
}

func (x BuilderConfig_Id_Type) String() string {
	return proto.EnumName(BuilderConfig_Id_Type_name, int32(x))
}

func (BuilderConfig_Id_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 0, 0}
}

// How to handle the uploading of prebuilts.
type BuilderConfig_Artifacts_Prebuilts int32

const (
	BuilderConfig_Artifacts_PREBUILTS_UNSPECIFIED BuilderConfig_Artifacts_Prebuilts = 0
	BuilderConfig_Artifacts_PUBLIC                BuilderConfig_Artifacts_Prebuilts = 1
	BuilderConfig_Artifacts_PRIVATE               BuilderConfig_Artifacts_Prebuilts = 2
	BuilderConfig_Artifacts_NONE                  BuilderConfig_Artifacts_Prebuilts = 3
)

var BuilderConfig_Artifacts_Prebuilts_name = map[int32]string{
	0: "PREBUILTS_UNSPECIFIED",
	1: "PUBLIC",
	2: "PRIVATE",
	3: "NONE",
}

var BuilderConfig_Artifacts_Prebuilts_value = map[string]int32{
	"PREBUILTS_UNSPECIFIED": 0,
	"PUBLIC":                1,
	"PRIVATE":               2,
	"NONE":                  3,
}

func (x BuilderConfig_Artifacts_Prebuilts) String() string {
	return proto.EnumName(BuilderConfig_Artifacts_Prebuilts_name, int32(x))
}

func (BuilderConfig_Artifacts_Prebuilts) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 3, 0}
}

// Used to indicate artifact types that should be uploaded by the builder.
// Must be kept in sync with the dictionary in:
// https://chromium.googlesource.com/chromiumos/infra/recipes/+/refs/heads/master/recipe_modules/cros_artifacts/api.py
type BuilderConfig_Artifacts_ArtifactTypes int32

const (
	BuilderConfig_Artifacts_ARTIFACT_TYPES_UNSPECIFIED BuilderConfig_Artifacts_ArtifactTypes = 0
	// Indicates wanting a zip file of everything in the image directory.
	BuilderConfig_Artifacts_IMAGE_ZIP BuilderConfig_Artifacts_ArtifactTypes = 1
	// Indicates wanting update payloads.
	BuilderConfig_Artifacts_TEST_UPDATE_PAYLOAD BuilderConfig_Artifacts_ArtifactTypes = 2
	// Indicates wanting the autotest tarballs.
	BuilderConfig_Artifacts_AUTOTEST_FILES BuilderConfig_Artifacts_ArtifactTypes = 3
	// Indicates wanting a tarball containing private TAST test bundles.
	BuilderConfig_Artifacts_TAST_FILES BuilderConfig_Artifacts_ArtifactTypes = 4
	// Indicates wanting a tarball containing guest images and test bundles.
	BuilderConfig_Artifacts_PINNED_GUEST_IMAGES BuilderConfig_Artifacts_ArtifactTypes = 5
	// Indicates wanting an archive of firmware images built from source.
	BuilderConfig_Artifacts_FIRMWARE BuilderConfig_Artifacts_ArtifactTypes = 6
	// Indicates wanting a tarball of the Ebuilds logs.
	BuilderConfig_Artifacts_EBUILD_LOGS BuilderConfig_Artifacts_ArtifactTypes = 7
)

var BuilderConfig_Artifacts_ArtifactTypes_name = map[int32]string{
	0: "ARTIFACT_TYPES_UNSPECIFIED",
	1: "IMAGE_ZIP",
	2: "TEST_UPDATE_PAYLOAD",
	3: "AUTOTEST_FILES",
	4: "TAST_FILES",
	5: "PINNED_GUEST_IMAGES",
	6: "FIRMWARE",
	7: "EBUILD_LOGS",
}

var BuilderConfig_Artifacts_ArtifactTypes_value = map[string]int32{
	"ARTIFACT_TYPES_UNSPECIFIED": 0,
	"IMAGE_ZIP":                  1,
	"TEST_UPDATE_PAYLOAD":        2,
	"AUTOTEST_FILES":             3,
	"TAST_FILES":                 4,
	"PINNED_GUEST_IMAGES":        5,
	"FIRMWARE":                   6,
	"EBUILD_LOGS":                7,
}

func (x BuilderConfig_Artifacts_ArtifactTypes) String() string {
	return proto.EnumName(BuilderConfig_Artifacts_ArtifactTypes_name, int32(x))
}

func (BuilderConfig_Artifacts_ArtifactTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 3, 1}
}

// Configuration used by a builder during execution.
type BuilderConfig struct {
	Id                   *BuilderConfig_Id           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	General              *BuilderConfig_General      `protobuf:"bytes,2,opt,name=general,proto3" json:"general,omitempty"`
	Orchestrator         *BuilderConfig_Orchestrator `protobuf:"bytes,3,opt,name=orchestrator,proto3" json:"orchestrator,omitempty"`
	Artifacts            *BuilderConfig_Artifacts    `protobuf:"bytes,4,opt,name=artifacts,proto3" json:"artifacts,omitempty"`
	Chrome               *BuilderConfig_Chrome       `protobuf:"bytes,5,opt,name=chrome,proto3" json:"chrome,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BuilderConfig) Reset()         { *m = BuilderConfig{} }
func (m *BuilderConfig) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig) ProtoMessage()    {}
func (*BuilderConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0}
}

func (m *BuilderConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig.Unmarshal(m, b)
}
func (m *BuilderConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig.Marshal(b, m, deterministic)
}
func (m *BuilderConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig.Merge(m, src)
}
func (m *BuilderConfig) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig.Size(m)
}
func (m *BuilderConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig proto.InternalMessageInfo

func (m *BuilderConfig) GetId() *BuilderConfig_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *BuilderConfig) GetGeneral() *BuilderConfig_General {
	if m != nil {
		return m.General
	}
	return nil
}

func (m *BuilderConfig) GetOrchestrator() *BuilderConfig_Orchestrator {
	if m != nil {
		return m.Orchestrator
	}
	return nil
}

func (m *BuilderConfig) GetArtifacts() *BuilderConfig_Artifacts {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

func (m *BuilderConfig) GetChrome() *BuilderConfig_Chrome {
	if m != nil {
		return m.Chrome
	}
	return nil
}

// Unique identifier of the builder configuration.
type BuilderConfig_Id struct {
	// The name of the configuration such as "arm-generic-postsubmit".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Branch the configuration applies to such as "release-R73-11647.B".
	Branch               string                `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Type                 BuilderConfig_Id_Type `protobuf:"varint,3,opt,name=type,proto3,enum=chromiumos.BuilderConfig_Id_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BuilderConfig_Id) Reset()         { *m = BuilderConfig_Id{} }
func (m *BuilderConfig_Id) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Id) ProtoMessage()    {}
func (*BuilderConfig_Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 0}
}

func (m *BuilderConfig_Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Id.Unmarshal(m, b)
}
func (m *BuilderConfig_Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Id.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Id.Merge(m, src)
}
func (m *BuilderConfig_Id) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Id.Size(m)
}
func (m *BuilderConfig_Id) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Id.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Id proto.InternalMessageInfo

func (m *BuilderConfig_Id) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BuilderConfig_Id) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *BuilderConfig_Id) GetType() BuilderConfig_Id_Type {
	if m != nil {
		return m.Type
	}
	return BuilderConfig_Id_TYPE_UNSPECIFIED
}

// General configuration for the builder.
type BuilderConfig_General struct {
	// Whether or not the build is considered critical. A failure in a critical
	// build for a CQ builder may, for example, prevent submission of the CL.
	Critical             *wrappers.BoolValue `protobuf:"bytes,1,opt,name=critical,proto3" json:"critical,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BuilderConfig_General) Reset()         { *m = BuilderConfig_General{} }
func (m *BuilderConfig_General) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_General) ProtoMessage()    {}
func (*BuilderConfig_General) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 1}
}

func (m *BuilderConfig_General) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_General.Unmarshal(m, b)
}
func (m *BuilderConfig_General) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_General.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_General) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_General.Merge(m, src)
}
func (m *BuilderConfig_General) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_General.Size(m)
}
func (m *BuilderConfig_General) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_General.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_General proto.InternalMessageInfo

func (m *BuilderConfig_General) GetCritical() *wrappers.BoolValue {
	if m != nil {
		return m.Critical
	}
	return nil
}

// Configuration pertaining to builders operating as "orchestrators".
// Orchestrators orchestrate the running of other child builders.
type BuilderConfig_Orchestrator struct {
	// BuilderConfig.Id.name of the child builds. They would expect to match
	// this name and the BuilderConfig.Id.branch and BuilderConfig.Id.type of
	// this parent orchestrator builder.
	Children             []string `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuilderConfig_Orchestrator) Reset()         { *m = BuilderConfig_Orchestrator{} }
func (m *BuilderConfig_Orchestrator) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Orchestrator) ProtoMessage()    {}
func (*BuilderConfig_Orchestrator) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 2}
}

func (m *BuilderConfig_Orchestrator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Orchestrator.Unmarshal(m, b)
}
func (m *BuilderConfig_Orchestrator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Orchestrator.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Orchestrator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Orchestrator.Merge(m, src)
}
func (m *BuilderConfig_Orchestrator) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Orchestrator.Size(m)
}
func (m *BuilderConfig_Orchestrator) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Orchestrator.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Orchestrator proto.InternalMessageInfo

func (m *BuilderConfig_Orchestrator) GetChildren() []string {
	if m != nil {
		return m.Children
	}
	return nil
}

// Configuration pertaining to artifacts produced during a build.
type BuilderConfig_Artifacts struct {
	Prebuilts            BuilderConfig_Artifacts_Prebuilts       `protobuf:"varint,1,opt,name=prebuilts,proto3,enum=chromiumos.BuilderConfig_Artifacts_Prebuilts" json:"prebuilts,omitempty"`
	ArtifactTypes        []BuilderConfig_Artifacts_ArtifactTypes `protobuf:"varint,2,rep,packed,name=artifact_types,json=artifactTypes,proto3,enum=chromiumos.BuilderConfig_Artifacts_ArtifactTypes" json:"artifact_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *BuilderConfig_Artifacts) Reset()         { *m = BuilderConfig_Artifacts{} }
func (m *BuilderConfig_Artifacts) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Artifacts) ProtoMessage()    {}
func (*BuilderConfig_Artifacts) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 3}
}

func (m *BuilderConfig_Artifacts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Artifacts.Unmarshal(m, b)
}
func (m *BuilderConfig_Artifacts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Artifacts.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Artifacts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Artifacts.Merge(m, src)
}
func (m *BuilderConfig_Artifacts) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Artifacts.Size(m)
}
func (m *BuilderConfig_Artifacts) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Artifacts.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Artifacts proto.InternalMessageInfo

func (m *BuilderConfig_Artifacts) GetPrebuilts() BuilderConfig_Artifacts_Prebuilts {
	if m != nil {
		return m.Prebuilts
	}
	return BuilderConfig_Artifacts_PREBUILTS_UNSPECIFIED
}

func (m *BuilderConfig_Artifacts) GetArtifactTypes() []BuilderConfig_Artifacts_ArtifactTypes {
	if m != nil {
		return m.ArtifactTypes
	}
	return nil
}

// Configuration pertaining to Chrome.
type BuilderConfig_Chrome struct {
	// Whether to build internal or external Chrome. Internal chrome adds
	// Chrome branding.
	Internal             bool     `protobuf:"varint,1,opt,name=internal,proto3" json:"internal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuilderConfig_Chrome) Reset()         { *m = BuilderConfig_Chrome{} }
func (m *BuilderConfig_Chrome) String() string { return proto.CompactTextString(m) }
func (*BuilderConfig_Chrome) ProtoMessage()    {}
func (*BuilderConfig_Chrome) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{0, 4}
}

func (m *BuilderConfig_Chrome) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfig_Chrome.Unmarshal(m, b)
}
func (m *BuilderConfig_Chrome) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfig_Chrome.Marshal(b, m, deterministic)
}
func (m *BuilderConfig_Chrome) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfig_Chrome.Merge(m, src)
}
func (m *BuilderConfig_Chrome) XXX_Size() int {
	return xxx_messageInfo_BuilderConfig_Chrome.Size(m)
}
func (m *BuilderConfig_Chrome) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfig_Chrome.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfig_Chrome proto.InternalMessageInfo

func (m *BuilderConfig_Chrome) GetInternal() bool {
	if m != nil {
		return m.Internal
	}
	return false
}

// List of builder configs. Intended to be serialized to / from disk.
type BuilderConfigs struct {
	BuilderConfigs       []*BuilderConfig `protobuf:"bytes,1,rep,name=builder_configs,json=builderConfigs,proto3" json:"builder_configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BuilderConfigs) Reset()         { *m = BuilderConfigs{} }
func (m *BuilderConfigs) String() string { return proto.CompactTextString(m) }
func (*BuilderConfigs) ProtoMessage()    {}
func (*BuilderConfigs) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe67302c16003fb, []int{1}
}

func (m *BuilderConfigs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuilderConfigs.Unmarshal(m, b)
}
func (m *BuilderConfigs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuilderConfigs.Marshal(b, m, deterministic)
}
func (m *BuilderConfigs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuilderConfigs.Merge(m, src)
}
func (m *BuilderConfigs) XXX_Size() int {
	return xxx_messageInfo_BuilderConfigs.Size(m)
}
func (m *BuilderConfigs) XXX_DiscardUnknown() {
	xxx_messageInfo_BuilderConfigs.DiscardUnknown(m)
}

var xxx_messageInfo_BuilderConfigs proto.InternalMessageInfo

func (m *BuilderConfigs) GetBuilderConfigs() []*BuilderConfig {
	if m != nil {
		return m.BuilderConfigs
	}
	return nil
}

func init() {
	proto.RegisterEnum("chromiumos.BuilderConfig_Id_Type", BuilderConfig_Id_Type_name, BuilderConfig_Id_Type_value)
	proto.RegisterEnum("chromiumos.BuilderConfig_Artifacts_Prebuilts", BuilderConfig_Artifacts_Prebuilts_name, BuilderConfig_Artifacts_Prebuilts_value)
	proto.RegisterEnum("chromiumos.BuilderConfig_Artifacts_ArtifactTypes", BuilderConfig_Artifacts_ArtifactTypes_name, BuilderConfig_Artifacts_ArtifactTypes_value)
	proto.RegisterType((*BuilderConfig)(nil), "chromiumos.BuilderConfig")
	proto.RegisterType((*BuilderConfig_Id)(nil), "chromiumos.BuilderConfig.Id")
	proto.RegisterType((*BuilderConfig_General)(nil), "chromiumos.BuilderConfig.General")
	proto.RegisterType((*BuilderConfig_Orchestrator)(nil), "chromiumos.BuilderConfig.Orchestrator")
	proto.RegisterType((*BuilderConfig_Artifacts)(nil), "chromiumos.BuilderConfig.Artifacts")
	proto.RegisterType((*BuilderConfig_Chrome)(nil), "chromiumos.BuilderConfig.Chrome")
	proto.RegisterType((*BuilderConfigs)(nil), "chromiumos.BuilderConfigs")
}

func init() { proto.RegisterFile("chromiumos/builder_config.proto", fileDescriptor_6fe67302c16003fb) }

var fileDescriptor_6fe67302c16003fb = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5f, 0x6f, 0xd2, 0x50,
	0x1c, 0xb5, 0x85, 0x01, 0xfd, 0x31, 0xba, 0xe6, 0xfa, 0x8f, 0x35, 0x66, 0x22, 0x1a, 0xb3, 0x18,
	0x2d, 0x11, 0xe7, 0x62, 0xe2, 0x53, 0x81, 0x42, 0xae, 0x32, 0xa8, 0xb7, 0x65, 0xba, 0xbd, 0x34,
	0xa5, 0x14, 0x68, 0xc2, 0x7a, 0xc9, 0x6d, 0x89, 0xd9, 0x87, 0xf1, 0x2b, 0xf8, 0xb2, 0x2f, 0x68,
	0x7a, 0x81, 0x02, 0x4b, 0x30, 0x7b, 0xeb, 0xaf, 0xf7, 0x9c, 0x73, 0x73, 0xcf, 0x39, 0xf9, 0xc1,
	0x4b, 0x6f, 0xca, 0xe8, 0x4d, 0xb0, 0xb8, 0xa1, 0x51, 0x6d, 0xb8, 0x08, 0x66, 0x23, 0x9f, 0x39,
	0x1e, 0x0d, 0xc7, 0xc1, 0x44, 0x9b, 0x33, 0x1a, 0x53, 0x04, 0x1b, 0x80, 0x7a, 0x32, 0xa1, 0x74,
	0x32, 0xf3, 0x6b, 0xfc, 0x64, 0xb8, 0x18, 0xd7, 0x7e, 0x33, 0x77, 0x3e, 0xf7, 0x59, 0xb4, 0xc4,
	0x56, 0xff, 0x16, 0xa0, 0xd4, 0x58, 0x8a, 0x34, 0xb9, 0x06, 0x7a, 0x0f, 0x62, 0x30, 0x2a, 0x0b,
	0x15, 0xe1, 0xb4, 0x58, 0x7f, 0xa1, 0x6d, 0xa4, 0xb4, 0x1d, 0x98, 0x86, 0x47, 0x44, 0x0c, 0x46,
	0xe8, 0x2b, 0xe4, 0x27, 0x7e, 0xe8, 0x33, 0x77, 0x56, 0x16, 0x39, 0xe5, 0xd5, 0x7e, 0x4a, 0x67,
	0x09, 0x24, 0x6b, 0x06, 0xfa, 0x06, 0x87, 0x94, 0x79, 0x53, 0x3f, 0x8a, 0x99, 0x1b, 0x53, 0x56,
	0xce, 0x70, 0x85, 0xb7, 0xfb, 0x15, 0xfa, 0x5b, 0x68, 0xb2, 0xc3, 0x45, 0x3a, 0x48, 0x2e, 0x8b,
	0x83, 0xb1, 0xeb, 0xc5, 0x51, 0x39, 0xcb, 0x85, 0x5e, 0xef, 0x17, 0xd2, 0xd7, 0x50, 0xb2, 0x61,
	0xa1, 0x2f, 0x90, 0xe3, 0x04, 0xbf, 0x7c, 0xc0, 0xf9, 0x95, 0xfd, 0xfc, 0x26, 0xc7, 0x91, 0x15,
	0x5e, 0xfd, 0x23, 0x80, 0x88, 0x47, 0x08, 0x41, 0x36, 0x74, 0x6f, 0x7c, 0x6e, 0x9e, 0x44, 0xf8,
	0x37, 0x7a, 0x06, 0xb9, 0x21, 0x73, 0x43, 0x6f, 0xca, 0xfd, 0x91, 0xc8, 0x6a, 0x42, 0x9f, 0x21,
	0x1b, 0xdf, 0xce, 0x7d, 0xfe, 0x66, 0xf9, 0x7f, 0xae, 0xe1, 0x91, 0x66, 0xdf, 0xce, 0x7d, 0xc2,
	0xe1, 0xd5, 0x33, 0xc8, 0x26, 0x13, 0x7a, 0x02, 0x8a, 0x7d, 0x65, 0x1a, 0xce, 0xa0, 0x67, 0x99,
	0x46, 0x13, 0xb7, 0xb1, 0xd1, 0x52, 0x1e, 0xa1, 0x1c, 0x88, 0xcd, 0x1f, 0x8a, 0x80, 0x64, 0x00,
	0xb3, 0x6f, 0xd9, 0xd6, 0xa0, 0x71, 0x81, 0x6d, 0x45, 0x54, 0x75, 0xc8, 0xaf, 0xcc, 0x47, 0xe7,
	0x50, 0xf0, 0x58, 0x10, 0x07, 0x9e, 0x3b, 0x5b, 0x85, 0xac, 0x6a, 0xcb, 0x8e, 0x68, 0xeb, 0x8e,
	0x68, 0x0d, 0x4a, 0x67, 0x97, 0xee, 0x6c, 0xe1, 0x93, 0x14, 0xab, 0xbe, 0x83, 0xc3, 0x6d, 0xf7,
	0x91, 0x0a, 0x05, 0x6f, 0x1a, 0xcc, 0x46, 0xcc, 0x0f, 0xcb, 0x42, 0x25, 0x73, 0x2a, 0x91, 0x74,
	0x56, 0xef, 0x32, 0x20, 0xa5, 0x0e, 0xa3, 0xef, 0x20, 0xcd, 0x99, 0x9f, 0x34, 0x35, 0x8e, 0xf8,
	0x95, 0x72, 0xfd, 0xc3, 0x03, 0x92, 0xd1, 0xcc, 0x35, 0x89, 0x6c, 0xf8, 0xe8, 0x17, 0xc8, 0xeb,
	0xc0, 0x9c, 0xc4, 0x90, 0xa8, 0x2c, 0x56, 0x32, 0xa7, 0x72, 0xfd, 0xe3, 0x43, 0x14, 0xd7, 0x5f,
	0x89, 0x83, 0x11, 0x29, 0xb9, 0xdb, 0x63, 0x15, 0x83, 0x94, 0xde, 0x88, 0x8e, 0xe1, 0xa9, 0x49,
	0x8c, 0xc6, 0x00, 0x77, 0x6d, 0xeb, 0x9e, 0xc7, 0x00, 0x39, 0x73, 0xd0, 0xe8, 0xe2, 0xa6, 0x22,
	0xa0, 0x22, 0xe4, 0x4d, 0x82, 0x2f, 0x75, 0xdb, 0x50, 0x44, 0x54, 0x80, 0x6c, 0xaf, 0xdf, 0x33,
	0x94, 0x4c, 0xf5, 0x4e, 0x80, 0xd2, 0xce, 0x5d, 0xe8, 0x04, 0x54, 0x9d, 0xd8, 0xb8, 0xad, 0x37,
	0x6d, 0x27, 0xc9, 0xed, 0xbe, 0x68, 0x09, 0x24, 0x7c, 0xa1, 0x77, 0x0c, 0xe7, 0x1a, 0x9b, 0x8a,
	0x80, 0x9e, 0xc3, 0x63, 0xdb, 0xb0, 0x6c, 0x67, 0x60, 0xb6, 0x74, 0xdb, 0x70, 0x4c, 0xfd, 0xaa,
	0xdb, 0xd7, 0x5b, 0x8a, 0x88, 0x10, 0xc8, 0xfa, 0xc0, 0xee, 0xf3, 0xc3, 0x36, 0xee, 0x1a, 0x96,
	0x92, 0x49, 0xc2, 0xb6, 0xf5, 0x74, 0xce, 0x26, 0x64, 0x13, 0xf7, 0x7a, 0x46, 0xcb, 0xe9, 0x0c,
	0x12, 0x1c, 0x17, 0xb6, 0x94, 0x03, 0x74, 0x08, 0x85, 0x36, 0x26, 0x17, 0x3f, 0x75, 0x62, 0x28,
	0x39, 0x74, 0x04, 0x45, 0xfe, 0xc0, 0x96, 0xd3, 0xed, 0x77, 0x2c, 0x25, 0xaf, 0xbe, 0x81, 0xdc,
	0xb2, 0xd6, 0x49, 0xb6, 0x41, 0x18, 0xfb, 0x2c, 0x5c, 0x75, 0xa4, 0x40, 0xd2, 0xb9, 0x6a, 0x83,
	0xbc, 0x63, 0x6f, 0x84, 0x1a, 0x70, 0xb4, 0xbb, 0x86, 0x22, 0x5e, 0x88, 0x62, 0xfd, 0x78, 0x6f,
	0x26, 0x44, 0x1e, 0xee, 0x68, 0x34, 0xce, 0xaf, 0xcf, 0x26, 0x34, 0x85, 0x6b, 0x94, 0x4d, 0x6a,
	0x5b, 0x5b, 0x2e, 0x08, 0xc7, 0xcc, 0x5d, 0xae, 0xb0, 0xda, 0x84, 0x6e, 0x9d, 0x0c, 0x73, 0xfc,
	0xe7, 0xa7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x6e, 0x48, 0xba, 0x14, 0x05, 0x00, 0x00,
}
