// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/common.proto

package chromiumos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BuildTarget encapsulates a number of related arguments. At the moment, the
// usage of specific arguments is on a per endpoint basis, but will converge
// to support a standard set as time goes on.
// BuildTarget is a more appropriate name going forward for what we currently
// call "board".
type BuildTarget struct {
	// The name of the build target (a.k.a. board name).
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildTarget) Reset()         { *m = BuildTarget{} }
func (m *BuildTarget) String() string { return proto.CompactTextString(m) }
func (*BuildTarget) ProtoMessage()    {}
func (*BuildTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa0b57c3d7d4c63b, []int{0}
}

func (m *BuildTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTarget.Unmarshal(m, b)
}
func (m *BuildTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTarget.Marshal(b, m, deterministic)
}
func (m *BuildTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTarget.Merge(m, src)
}
func (m *BuildTarget) XXX_Size() int {
	return xxx_messageInfo_BuildTarget.Size(m)
}
func (m *BuildTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTarget.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTarget proto.InternalMessageInfo

func (m *BuildTarget) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Message describing a package, The corresponding variable names are from
// https://devmanual.gentoo.org/ebuild-writing/variables/index.html
type PackageInfo struct {
	// The package name (PN variable).
	PackageName string `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// The package category (CATEGORY variable).
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// The package version and revision (PVR variable).
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageInfo) Reset()         { *m = PackageInfo{} }
func (m *PackageInfo) String() string { return proto.CompactTextString(m) }
func (*PackageInfo) ProtoMessage()    {}
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa0b57c3d7d4c63b, []int{1}
}

func (m *PackageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageInfo.Unmarshal(m, b)
}
func (m *PackageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageInfo.Marshal(b, m, deterministic)
}
func (m *PackageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageInfo.Merge(m, src)
}
func (m *PackageInfo) XXX_Size() int {
	return xxx_messageInfo_PackageInfo.Size(m)
}
func (m *PackageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PackageInfo proto.InternalMessageInfo

func (m *PackageInfo) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *PackageInfo) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *PackageInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*BuildTarget)(nil), "chromiumos.BuildTarget")
	proto.RegisterType((*PackageInfo)(nil), "chromiumos.PackageInfo")
}

func init() { proto.RegisterFile("chromiumos/common.proto", fileDescriptor_fa0b57c3d7d4c63b) }

var fileDescriptor_fa0b57c3d7d4c63b = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3f, 0x0b, 0xc2, 0x30,
	0x10, 0xc5, 0xa9, 0x8a, 0x7f, 0xae, 0x4e, 0x59, 0x0c, 0x4e, 0xb6, 0x93, 0x53, 0x33, 0x28, 0x7e,
	0x80, 0x6e, 0x2e, 0x22, 0xe2, 0xe4, 0x22, 0x31, 0xa6, 0x31, 0x68, 0x72, 0xe5, 0xda, 0x0a, 0x7e,
	0x7b, 0x21, 0x5a, 0xed, 0x76, 0xbf, 0xf7, 0xbb, 0xe1, 0x3d, 0x98, 0xa9, 0x1b, 0xa1, 0xb3, 0x8d,
	0xc3, 0x4a, 0x28, 0x74, 0x0e, 0x7d, 0x56, 0x12, 0xd6, 0xc8, 0xe0, 0x2f, 0xd2, 0x04, 0xe2, 0xbc,
	0xb1, 0x8f, 0xeb, 0x51, 0x92, 0xd1, 0x35, 0x63, 0x30, 0xf0, 0xd2, 0x69, 0x1e, 0x2d, 0xa2, 0xe5,
	0xe4, 0x10, 0xee, 0xb4, 0x80, 0x78, 0x2f, 0xd5, 0x5d, 0x1a, 0xbd, 0xf5, 0x05, 0xb2, 0x04, 0xa6,
	0xe5, 0x07, 0xcf, 0x9d, 0xd7, 0xf8, 0x9b, 0xed, 0xa4, 0xd3, 0x6c, 0x0e, 0x63, 0x25, 0x6b, 0x6d,
	0x90, 0x5e, 0xbc, 0x17, 0xf4, 0x8f, 0x19, 0x87, 0xd1, 0x53, 0x53, 0x65, 0xd1, 0xf3, 0x7e, 0x50,
	0x2d, 0xe6, 0x9b, 0xd3, 0xda, 0x60, 0xd6, 0x76, 0xcb, 0x90, 0x8c, 0xe8, 0x2c, 0xb0, 0xbe, 0x20,
	0x29, 0xc2, 0x00, 0x61, 0xb0, 0x63, 0x2e, 0xc3, 0x10, 0xae, 0xde, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x32, 0xbc, 0x40, 0x13, 0xf0, 0x00, 0x00, 0x00,
}
