// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromiumos/pointless_build.proto

package chromiumos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PointlessBuildCheckResponse_PointlessBuildReason int32

const (
	PointlessBuildCheckResponse_POINTLESS_BUILD_REASON_UNSPECIFIED          PointlessBuildCheckResponse_PointlessBuildReason = 0
	PointlessBuildCheckResponse_IRRELEVANT_TO_DEPS_GRAPH                    PointlessBuildCheckResponse_PointlessBuildReason = 1
	PointlessBuildCheckResponse_IRRELEVANT_TO_KNOWN_NON_PORTAGE_DIRECTORIES PointlessBuildCheckResponse_PointlessBuildReason = 2
)

var PointlessBuildCheckResponse_PointlessBuildReason_name = map[int32]string{
	0: "POINTLESS_BUILD_REASON_UNSPECIFIED",
	1: "IRRELEVANT_TO_DEPS_GRAPH",
	2: "IRRELEVANT_TO_KNOWN_NON_PORTAGE_DIRECTORIES",
}

var PointlessBuildCheckResponse_PointlessBuildReason_value = map[string]int32{
	"POINTLESS_BUILD_REASON_UNSPECIFIED":          0,
	"IRRELEVANT_TO_DEPS_GRAPH":                    1,
	"IRRELEVANT_TO_KNOWN_NON_PORTAGE_DIRECTORIES": 2,
}

func (x PointlessBuildCheckResponse_PointlessBuildReason) String() string {
	return proto.EnumName(PointlessBuildCheckResponse_PointlessBuildReason_name, int32(x))
}

func (PointlessBuildCheckResponse_PointlessBuildReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5dbad4bc811f42a, []int{2, 0}
}

type ProtoBytes struct {
	SerializedProto      []byte   `protobuf:"bytes,1,opt,name=serialized_proto,json=serializedProto,proto3" json:"serialized_proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoBytes) Reset()         { *m = ProtoBytes{} }
func (m *ProtoBytes) String() string { return proto.CompactTextString(m) }
func (*ProtoBytes) ProtoMessage()    {}
func (*ProtoBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5dbad4bc811f42a, []int{0}
}

func (m *ProtoBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoBytes.Unmarshal(m, b)
}
func (m *ProtoBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoBytes.Marshal(b, m, deterministic)
}
func (m *ProtoBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoBytes.Merge(m, src)
}
func (m *ProtoBytes) XXX_Size() int {
	return xxx_messageInfo_ProtoBytes.Size(m)
}
func (m *ProtoBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoBytes.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoBytes proto.InternalMessageInfo

func (m *ProtoBytes) GetSerializedProto() []byte {
	if m != nil {
		return m.SerializedProto
	}
	return nil
}

// The input proto for invocations of the Pointless Build Checker program.
type PointlessBuildCheckRequest struct {
	// Serialized buildbucket Build proto for this child builder run.
	// See https://chromium.googlesource.com/infra/luci/luci-go/+/master/buildbucket/proto/build.proto
	BuildbucketProto *ProtoBytes `protobuf:"bytes,1,opt,name=buildbucket_proto,json=buildbucketProto,proto3" json:"buildbucket_proto,omitempty"`
	// Path on disk to a JSON-encoded chromite.api.DepGraph for this child
	// builder.
	DepGraphPath string `protobuf:"bytes,2,opt,name=dep_graph_path,json=depGraphPath,proto3" json:"dep_graph_path,omitempty"`
	// Path on disk to the chromiumos workspace repo checkout.
	ChromiumosWorkspaceCheckoutRoot string `protobuf:"bytes,3,opt,name=chromiumos_workspace_checkout_root,json=chromiumosWorkspaceCheckoutRoot,proto3" json:"chromiumos_workspace_checkout_root,omitempty"`
	// Path on disk to the "repo" CLI tool.
	RepoToolPath         string   `protobuf:"bytes,4,opt,name=repo_tool_path,json=repoToolPath,proto3" json:"repo_tool_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointlessBuildCheckRequest) Reset()         { *m = PointlessBuildCheckRequest{} }
func (m *PointlessBuildCheckRequest) String() string { return proto.CompactTextString(m) }
func (*PointlessBuildCheckRequest) ProtoMessage()    {}
func (*PointlessBuildCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5dbad4bc811f42a, []int{1}
}

func (m *PointlessBuildCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointlessBuildCheckRequest.Unmarshal(m, b)
}
func (m *PointlessBuildCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointlessBuildCheckRequest.Marshal(b, m, deterministic)
}
func (m *PointlessBuildCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointlessBuildCheckRequest.Merge(m, src)
}
func (m *PointlessBuildCheckRequest) XXX_Size() int {
	return xxx_messageInfo_PointlessBuildCheckRequest.Size(m)
}
func (m *PointlessBuildCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PointlessBuildCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PointlessBuildCheckRequest proto.InternalMessageInfo

func (m *PointlessBuildCheckRequest) GetBuildbucketProto() *ProtoBytes {
	if m != nil {
		return m.BuildbucketProto
	}
	return nil
}

func (m *PointlessBuildCheckRequest) GetDepGraphPath() string {
	if m != nil {
		return m.DepGraphPath
	}
	return ""
}

func (m *PointlessBuildCheckRequest) GetChromiumosWorkspaceCheckoutRoot() string {
	if m != nil {
		return m.ChromiumosWorkspaceCheckoutRoot
	}
	return ""
}

func (m *PointlessBuildCheckRequest) GetRepoToolPath() string {
	if m != nil {
		return m.RepoToolPath
	}
	return ""
}

// The output proto for invocations of the Pointless Build Checker program.
type PointlessBuildCheckResponse struct {
	// Whether the build is pointless and can be terminated without proceeding to
	// building packages and testing.
	BuildIsPointless *wrappers.BoolValue `protobuf:"bytes,1,opt,name=build_is_pointless,json=buildIsPointless,proto3" json:"build_is_pointless,omitempty"`
	// If build_is_pointless, this is the reason that the Pointless Build Checker
	// came to that conclusion. Otherwise, this is unspecified.
	PointlessBuildReason PointlessBuildCheckResponse_PointlessBuildReason `protobuf:"varint,2,opt,name=pointless_build_reason,json=pointlessBuildReason,proto3,enum=chromiumos.PointlessBuildCheckResponse_PointlessBuildReason" json:"pointless_build_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *PointlessBuildCheckResponse) Reset()         { *m = PointlessBuildCheckResponse{} }
func (m *PointlessBuildCheckResponse) String() string { return proto.CompactTextString(m) }
func (*PointlessBuildCheckResponse) ProtoMessage()    {}
func (*PointlessBuildCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5dbad4bc811f42a, []int{2}
}

func (m *PointlessBuildCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointlessBuildCheckResponse.Unmarshal(m, b)
}
func (m *PointlessBuildCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointlessBuildCheckResponse.Marshal(b, m, deterministic)
}
func (m *PointlessBuildCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointlessBuildCheckResponse.Merge(m, src)
}
func (m *PointlessBuildCheckResponse) XXX_Size() int {
	return xxx_messageInfo_PointlessBuildCheckResponse.Size(m)
}
func (m *PointlessBuildCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PointlessBuildCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PointlessBuildCheckResponse proto.InternalMessageInfo

func (m *PointlessBuildCheckResponse) GetBuildIsPointless() *wrappers.BoolValue {
	if m != nil {
		return m.BuildIsPointless
	}
	return nil
}

func (m *PointlessBuildCheckResponse) GetPointlessBuildReason() PointlessBuildCheckResponse_PointlessBuildReason {
	if m != nil {
		return m.PointlessBuildReason
	}
	return PointlessBuildCheckResponse_POINTLESS_BUILD_REASON_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("chromiumos.PointlessBuildCheckResponse_PointlessBuildReason", PointlessBuildCheckResponse_PointlessBuildReason_name, PointlessBuildCheckResponse_PointlessBuildReason_value)
	proto.RegisterType((*ProtoBytes)(nil), "chromiumos.ProtoBytes")
	proto.RegisterType((*PointlessBuildCheckRequest)(nil), "chromiumos.PointlessBuildCheckRequest")
	proto.RegisterType((*PointlessBuildCheckResponse)(nil), "chromiumos.PointlessBuildCheckResponse")
}

func init() { proto.RegisterFile("chromiumos/pointless_build.proto", fileDescriptor_c5dbad4bc811f42a) }

var fileDescriptor_c5dbad4bc811f42a = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0x4d, 0x15, 0xc1, 0x71, 0x59, 0xeb, 0xb0, 0x2c, 0xa5, 0x8a, 0x96, 0x20, 0xb2, 0x22,
	0x24, 0xb0, 0x8a, 0xde, 0x78, 0xd3, 0x8f, 0xd8, 0x0d, 0x5b, 0x92, 0x30, 0xc9, 0xee, 0x82, 0x37,
	0x87, 0xb4, 0x9d, 0x4d, 0x43, 0xb3, 0x3d, 0xe3, 0xcc, 0x84, 0x45, 0xdf, 0xc1, 0x27, 0xf5, 0x0d,
	0xbc, 0x92, 0x4c, 0xda, 0xa6, 0xbb, 0x74, 0xef, 0xc2, 0xff, 0xfc, 0xce, 0xf9, 0x9f, 0x8f, 0x0c,
	0xe9, 0xcd, 0x16, 0x12, 0x6f, 0xf2, 0xf2, 0x06, 0x95, 0x2b, 0x30, 0x5f, 0xe9, 0x82, 0x2b, 0x05,
	0xd3, 0x32, 0x2f, 0xe6, 0x8e, 0x90, 0xa8, 0x91, 0x92, 0x86, 0xe8, 0xbe, 0xc9, 0x10, 0xb3, 0x82,
	0xbb, 0x26, 0x32, 0x2d, 0xaf, 0xdd, 0x5b, 0x99, 0x0a, 0xc1, 0xa5, 0xaa, 0x59, 0xfb, 0x2b, 0x21,
	0x51, 0xf5, 0x31, 0xf8, 0xa5, 0xb9, 0xa2, 0x1f, 0x48, 0x5b, 0x71, 0x99, 0xa7, 0x45, 0xfe, 0x9b,
	0xcf, 0xc1, 0x10, 0x1d, 0xab, 0x67, 0x9d, 0x1c, 0xb0, 0x17, 0x8d, 0x6e, 0x78, 0xfb, 0x9f, 0x45,
	0xba, 0xd1, 0xc6, 0x7e, 0x50, 0xb9, 0x0f, 0x17, 0x7c, 0xb6, 0x64, 0xfc, 0x67, 0xc9, 0x95, 0xa6,
	0x43, 0xf2, 0xd2, 0xb4, 0x34, 0x2d, 0x67, 0x4b, 0xae, 0x77, 0x4a, 0x3d, 0x3f, 0x3d, 0x76, 0x9a,
	0xfe, 0x9c, 0xc6, 0x9c, 0xb5, 0x77, 0x12, 0x8c, 0x4c, 0xdf, 0x91, 0xc3, 0x39, 0x17, 0x90, 0xc9,
	0x54, 0x2c, 0x40, 0xa4, 0x7a, 0xd1, 0x69, 0xf5, 0xac, 0x93, 0x67, 0xec, 0x60, 0xce, 0xc5, 0xb8,
	0x12, 0xa3, 0x54, 0x2f, 0xe8, 0x39, 0xb1, 0x9b, 0x82, 0x70, 0x8b, 0x72, 0xa9, 0x44, 0x3a, 0xe3,
	0x30, 0xab, 0xfa, 0xc1, 0x52, 0x83, 0x44, 0xd4, 0x9d, 0xc7, 0x26, 0xf3, 0x6d, 0x43, 0x5e, 0x6d,
	0xc0, 0xe1, 0x9a, 0x63, 0x88, 0xba, 0xb2, 0x94, 0x5c, 0x20, 0x68, 0xc4, 0xa2, 0xb6, 0x7c, 0x52,
	0x5b, 0x56, 0x6a, 0x82, 0x58, 0x54, 0x96, 0xf6, 0xdf, 0x16, 0x79, 0xb5, 0x77, 0x78, 0x25, 0x70,
	0xa5, 0x38, 0x3d, 0x23, 0xd4, 0x0c, 0x03, 0xb9, 0x82, 0xed, 0x8d, 0xd6, 0xe3, 0x77, 0x9d, 0xfa,
	0x24, 0xce, 0xe6, 0x24, 0xce, 0x00, 0xb1, 0xb8, 0x4c, 0x8b, 0x92, 0xaf, 0x57, 0xe0, 0xab, 0x6d,
	0x6d, 0x2a, 0xc9, 0xf1, 0xbd, 0x23, 0x83, 0xe4, 0xa9, 0xc2, 0x95, 0x59, 0xc5, 0xe1, 0xe9, 0xb7,
	0x3b, 0xcb, 0x7c, 0xb8, 0xa5, 0x7b, 0x31, 0x66, 0x6a, 0xb0, 0x23, 0xb1, 0x47, 0xb5, 0xff, 0x58,
	0xe4, 0x68, 0x1f, 0x4e, 0xdf, 0x13, 0x3b, 0x0a, 0xfd, 0x20, 0x99, 0x78, 0x71, 0x0c, 0x83, 0x0b,
	0x7f, 0x32, 0x02, 0xe6, 0xf5, 0xe3, 0x30, 0x80, 0x8b, 0x20, 0x8e, 0xbc, 0xa1, 0xff, 0xdd, 0xf7,
	0x46, 0xed, 0x47, 0xf4, 0x35, 0xe9, 0xf8, 0x8c, 0x79, 0x13, 0xef, 0xb2, 0x1f, 0x24, 0x90, 0x84,
	0x30, 0xf2, 0xa2, 0x18, 0xc6, 0xac, 0x1f, 0x9d, 0xb5, 0x2d, 0xea, 0x92, 0x8f, 0x77, 0xa3, 0xe7,
	0x41, 0x78, 0x15, 0x40, 0x10, 0x06, 0x10, 0x85, 0x2c, 0xe9, 0x8f, 0x3d, 0x18, 0xf9, 0xcc, 0x1b,
	0x26, 0x21, 0xf3, 0xbd, 0xb8, 0xdd, 0x1a, 0x7c, 0xf9, 0xf1, 0x39, 0xc3, 0xed, 0x9c, 0x0e, 0xca,
	0xcc, 0xdd, 0x79, 0x03, 0xf9, 0xea, 0x5a, 0xa6, 0xf5, 0xff, 0xed, 0x66, 0xb8, 0x13, 0x99, 0x3e,
	0x35, 0xe2, 0xa7, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xbb, 0x2e, 0xb1, 0x32, 0x03, 0x00,
	0x00,
}
