// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testplans/common.proto

package testplans

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A unit of the CrOS codebase. As of 2019-01, this concept maps 1-to-1 with
// "paths" in the the internal and external full.xml files.
type SourceTree struct {
	// The path of a source tree,
	// e.g. "src/platform2" or "src/third_party/kernel/v4.19".
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceTree) Reset()         { *m = SourceTree{} }
func (m *SourceTree) String() string { return proto.CompactTextString(m) }
func (*SourceTree) ProtoMessage()    {}
func (*SourceTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_a516c54fffa1af30, []int{0}
}

func (m *SourceTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceTree.Unmarshal(m, b)
}
func (m *SourceTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceTree.Marshal(b, m, deterministic)
}
func (m *SourceTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceTree.Merge(m, src)
}
func (m *SourceTree) XXX_Size() int {
	return xxx_messageInfo_SourceTree.Size(m)
}
func (m *SourceTree) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceTree.DiscardUnknown(m)
}

var xxx_messageInfo_SourceTree proto.InternalMessageInfo

func (m *SourceTree) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ProtoBytes struct {
	SerializedProto      []byte   `protobuf:"bytes,1,opt,name=serialized_proto,json=serializedProto,proto3" json:"serialized_proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoBytes) Reset()         { *m = ProtoBytes{} }
func (m *ProtoBytes) String() string { return proto.CompactTextString(m) }
func (*ProtoBytes) ProtoMessage()    {}
func (*ProtoBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_a516c54fffa1af30, []int{1}
}

func (m *ProtoBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoBytes.Unmarshal(m, b)
}
func (m *ProtoBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoBytes.Marshal(b, m, deterministic)
}
func (m *ProtoBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoBytes.Merge(m, src)
}
func (m *ProtoBytes) XXX_Size() int {
	return xxx_messageInfo_ProtoBytes.Size(m)
}
func (m *ProtoBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoBytes.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoBytes proto.InternalMessageInfo

func (m *ProtoBytes) GetSerializedProto() []byte {
	if m != nil {
		return m.SerializedProto
	}
	return nil
}

func init() {
	proto.RegisterType((*SourceTree)(nil), "testplans.SourceTree")
	proto.RegisterType((*ProtoBytes)(nil), "testplans.ProtoBytes")
}

func init() { proto.RegisterFile("testplans/common.proto", fileDescriptor_a516c54fffa1af30) }

var fileDescriptor_a516c54fffa1af30 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x49, 0x2d, 0x2e,
	0x29, 0xc8, 0x49, 0xcc, 0x2b, 0xd6, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x8b, 0x2b, 0x29, 0x70, 0x71, 0x05, 0xe7, 0x97, 0x16, 0x25, 0xa7,
	0x86, 0x14, 0xa5, 0xa6, 0x0a, 0x09, 0x71, 0xb1, 0x14, 0x24, 0x96, 0x64, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0xe6, 0x5c, 0x5c, 0x01, 0x20, 0x5d, 0x4e, 0x95, 0x25, 0xa9,
	0xc5, 0x42, 0x9a, 0x5c, 0x02, 0xc5, 0xa9, 0x45, 0x99, 0x89, 0x39, 0x99, 0x55, 0xa9, 0x29, 0xf1,
	0x60, 0xe3, 0xc0, 0xaa, 0x79, 0x82, 0xf8, 0x11, 0xe2, 0x10, 0xf5, 0xa6, 0x51, 0xc6, 0xe9, 0xf9,
	0x7a, 0xc9, 0x19, 0x45, 0xf9, 0xb9, 0x99, 0xa5, 0xb9, 0x7a, 0xf9, 0x45, 0xe9, 0xfa, 0x30, 0x4e,
	0x7e, 0xb1, 0x7e, 0x66, 0x5e, 0x5a, 0x51, 0xa2, 0x3e, 0xd8, 0x00, 0xfd, 0xf4, 0x7c, 0x7d, 0xb8,
	0x8b, 0x92, 0xd8, 0xc0, 0x62, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xb6, 0x8c, 0xc3,
	0xbd, 0x00, 0x00, 0x00,
}
