// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testplans/generate_test_plan.proto

package testplans

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoBytes struct {
	SerializedProto      []byte   `protobuf:"bytes,1,opt,name=serialized_proto,json=serializedProto,proto3" json:"serialized_proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoBytes) Reset()         { *m = ProtoBytes{} }
func (m *ProtoBytes) String() string { return proto.CompactTextString(m) }
func (*ProtoBytes) ProtoMessage()    {}
func (*ProtoBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8083f85c67203f6, []int{0}
}

func (m *ProtoBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoBytes.Unmarshal(m, b)
}
func (m *ProtoBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoBytes.Marshal(b, m, deterministic)
}
func (m *ProtoBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoBytes.Merge(m, src)
}
func (m *ProtoBytes) XXX_Size() int {
	return xxx_messageInfo_ProtoBytes.Size(m)
}
func (m *ProtoBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoBytes.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoBytes proto.InternalMessageInfo

func (m *ProtoBytes) GetSerializedProto() []byte {
	if m != nil {
		return m.SerializedProto
	}
	return nil
}

type GenerateTestPlanRequest struct {
	// Path on disk to source_tree_test_config.cfg, which lives in chromite.
	SourceTreeConfigPath string `protobuf:"bytes,1,opt,name=source_tree_config_path,json=sourceTreeConfigPath,proto3" json:"source_tree_config_path,omitempty"`
	// Path on disk to target_test_requirements.cfg, which lives in chromite.
	TargetTestRequirementsPath string `protobuf:"bytes,2,opt,name=target_test_requirements_path,json=targetTestRequirementsPath,proto3" json:"target_test_requirements_path,omitempty"`
	// Serialized buildbucket Build protos that are part of this orchestrator run.
	// See https://chromium.googlesource.com/infra/luci/luci-go/+/master/buildbucket/proto/build.proto
	BuildbucketProtos []*ProtoBytes `protobuf:"bytes,5,rep,name=buildbucket_protos,json=buildbucketProtos,proto3" json:"buildbucket_protos,omitempty"`
	// Path on disk to the chromiumos repo checkout.
	ChromiumosCheckoutRoot string `protobuf:"bytes,4,opt,name=chromiumos_checkout_root,json=chromiumosCheckoutRoot,proto3" json:"chromiumos_checkout_root,omitempty"`
	// Path on disk to the "repo" CLI tool.
	RepoToolPath         string   `protobuf:"bytes,6,opt,name=repo_tool_path,json=repoToolPath,proto3" json:"repo_tool_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateTestPlanRequest) Reset()         { *m = GenerateTestPlanRequest{} }
func (m *GenerateTestPlanRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateTestPlanRequest) ProtoMessage()    {}
func (*GenerateTestPlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8083f85c67203f6, []int{1}
}

func (m *GenerateTestPlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTestPlanRequest.Unmarshal(m, b)
}
func (m *GenerateTestPlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTestPlanRequest.Marshal(b, m, deterministic)
}
func (m *GenerateTestPlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTestPlanRequest.Merge(m, src)
}
func (m *GenerateTestPlanRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateTestPlanRequest.Size(m)
}
func (m *GenerateTestPlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTestPlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTestPlanRequest proto.InternalMessageInfo

func (m *GenerateTestPlanRequest) GetSourceTreeConfigPath() string {
	if m != nil {
		return m.SourceTreeConfigPath
	}
	return ""
}

func (m *GenerateTestPlanRequest) GetTargetTestRequirementsPath() string {
	if m != nil {
		return m.TargetTestRequirementsPath
	}
	return ""
}

func (m *GenerateTestPlanRequest) GetBuildbucketProtos() []*ProtoBytes {
	if m != nil {
		return m.BuildbucketProtos
	}
	return nil
}

func (m *GenerateTestPlanRequest) GetChromiumosCheckoutRoot() string {
	if m != nil {
		return m.ChromiumosCheckoutRoot
	}
	return ""
}

func (m *GenerateTestPlanRequest) GetRepoToolPath() string {
	if m != nil {
		return m.RepoToolPath
	}
	return ""
}

// The final test plan.
type GenerateTestPlanResponse struct {
	TestUnit             []*TestUnit `protobuf:"bytes,1,rep,name=test_unit,json=testUnit,proto3" json:"test_unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenerateTestPlanResponse) Reset()         { *m = GenerateTestPlanResponse{} }
func (m *GenerateTestPlanResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateTestPlanResponse) ProtoMessage()    {}
func (*GenerateTestPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8083f85c67203f6, []int{2}
}

func (m *GenerateTestPlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateTestPlanResponse.Unmarshal(m, b)
}
func (m *GenerateTestPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateTestPlanResponse.Marshal(b, m, deterministic)
}
func (m *GenerateTestPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateTestPlanResponse.Merge(m, src)
}
func (m *GenerateTestPlanResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateTestPlanResponse.Size(m)
}
func (m *GenerateTestPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateTestPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateTestPlanResponse proto.InternalMessageInfo

func (m *GenerateTestPlanResponse) GetTestUnit() []*TestUnit {
	if m != nil {
		return m.TestUnit
	}
	return nil
}

// The files that should be tested in a test plan.
type BuildPayload struct {
	// The GS bucket in which artifacts for the build are stored, e.g.
	// gs://chromeos-image-archive
	ArtifactsGsBucket string `protobuf:"bytes,1,opt,name=artifacts_gs_bucket,json=artifactsGsBucket,proto3" json:"artifacts_gs_bucket,omitempty"`
	// The path in the bucket in which artifacts for the build are stored, e.g.
	// eve-paladin/R73-11588.0.0-rc4
	ArtifactsGsPath      string   `protobuf:"bytes,2,opt,name=artifacts_gs_path,json=artifactsGsPath,proto3" json:"artifacts_gs_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildPayload) Reset()         { *m = BuildPayload{} }
func (m *BuildPayload) String() string { return proto.CompactTextString(m) }
func (*BuildPayload) ProtoMessage()    {}
func (*BuildPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8083f85c67203f6, []int{3}
}

func (m *BuildPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildPayload.Unmarshal(m, b)
}
func (m *BuildPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildPayload.Marshal(b, m, deterministic)
}
func (m *BuildPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildPayload.Merge(m, src)
}
func (m *BuildPayload) XXX_Size() int {
	return xxx_messageInfo_BuildPayload.Size(m)
}
func (m *BuildPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BuildPayload proto.InternalMessageInfo

func (m *BuildPayload) GetArtifactsGsBucket() string {
	if m != nil {
		return m.ArtifactsGsBucket
	}
	return ""
}

func (m *BuildPayload) GetArtifactsGsPath() string {
	if m != nil {
		return m.ArtifactsGsPath
	}
	return ""
}

// Hardware or VM requirements for running a test plan.
type SchedulingRequirements struct {
	// Types that are valid to be assigned to TargetType:
	//	*SchedulingRequirements_BuildTarget
	TargetType           isSchedulingRequirements_TargetType `protobuf_oneof:"target_type"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *SchedulingRequirements) Reset()         { *m = SchedulingRequirements{} }
func (m *SchedulingRequirements) String() string { return proto.CompactTextString(m) }
func (*SchedulingRequirements) ProtoMessage()    {}
func (*SchedulingRequirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8083f85c67203f6, []int{4}
}

func (m *SchedulingRequirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchedulingRequirements.Unmarshal(m, b)
}
func (m *SchedulingRequirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchedulingRequirements.Marshal(b, m, deterministic)
}
func (m *SchedulingRequirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchedulingRequirements.Merge(m, src)
}
func (m *SchedulingRequirements) XXX_Size() int {
	return xxx_messageInfo_SchedulingRequirements.Size(m)
}
func (m *SchedulingRequirements) XXX_DiscardUnknown() {
	xxx_messageInfo_SchedulingRequirements.DiscardUnknown(m)
}

var xxx_messageInfo_SchedulingRequirements proto.InternalMessageInfo

type isSchedulingRequirements_TargetType interface {
	isSchedulingRequirements_TargetType()
}

type SchedulingRequirements_BuildTarget struct {
	BuildTarget string `protobuf:"bytes,2,opt,name=build_target,json=buildTarget,proto3,oneof"`
}

func (*SchedulingRequirements_BuildTarget) isSchedulingRequirements_TargetType() {}

func (m *SchedulingRequirements) GetTargetType() isSchedulingRequirements_TargetType {
	if m != nil {
		return m.TargetType
	}
	return nil
}

func (m *SchedulingRequirements) GetBuildTarget() string {
	if x, ok := m.GetTargetType().(*SchedulingRequirements_BuildTarget); ok {
		return x.BuildTarget
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SchedulingRequirements) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SchedulingRequirements_BuildTarget)(nil),
	}
}

// Metadata for executing one test configuration for one target type.
type TestUnit struct {
	// Types that are valid to be assigned to TestCfg:
	//	*TestUnit_GceTestCfg
	//	*TestUnit_HwTestCfg
	//	*TestUnit_MoblabVmTestCfg
	//	*TestUnit_TastVmTestCfg
	//	*TestUnit_VmTestCfg
	TestCfg isTestUnit_TestCfg `protobuf_oneof:"TestCfg"`
	// The scheduling requirements for this test plan.
	SchedulingRequirements *SchedulingRequirements `protobuf:"bytes,6,opt,name=scheduling_requirements,json=schedulingRequirements,proto3" json:"scheduling_requirements,omitempty"`
	// The build files provided to run this test plan.
	BuildPayload         *BuildPayload `protobuf:"bytes,7,opt,name=build_payload,json=buildPayload,proto3" json:"build_payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TestUnit) Reset()         { *m = TestUnit{} }
func (m *TestUnit) String() string { return proto.CompactTextString(m) }
func (*TestUnit) ProtoMessage()    {}
func (*TestUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_e8083f85c67203f6, []int{5}
}

func (m *TestUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestUnit.Unmarshal(m, b)
}
func (m *TestUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestUnit.Marshal(b, m, deterministic)
}
func (m *TestUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestUnit.Merge(m, src)
}
func (m *TestUnit) XXX_Size() int {
	return xxx_messageInfo_TestUnit.Size(m)
}
func (m *TestUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_TestUnit.DiscardUnknown(m)
}

var xxx_messageInfo_TestUnit proto.InternalMessageInfo

type isTestUnit_TestCfg interface {
	isTestUnit_TestCfg()
}

type TestUnit_GceTestCfg struct {
	GceTestCfg *GceTestCfg `protobuf:"bytes,1,opt,name=gce_test_cfg,json=gceTestCfg,proto3,oneof"`
}

type TestUnit_HwTestCfg struct {
	HwTestCfg *HwTestCfg `protobuf:"bytes,2,opt,name=hw_test_cfg,json=hwTestCfg,proto3,oneof"`
}

type TestUnit_MoblabVmTestCfg struct {
	MoblabVmTestCfg *MoblabVmTestCfg `protobuf:"bytes,3,opt,name=moblab_vm_test_cfg,json=moblabVmTestCfg,proto3,oneof"`
}

type TestUnit_TastVmTestCfg struct {
	TastVmTestCfg *TastVmTestCfg `protobuf:"bytes,4,opt,name=tast_vm_test_cfg,json=tastVmTestCfg,proto3,oneof"`
}

type TestUnit_VmTestCfg struct {
	VmTestCfg *VmTestCfg `protobuf:"bytes,5,opt,name=vm_test_cfg,json=vmTestCfg,proto3,oneof"`
}

func (*TestUnit_GceTestCfg) isTestUnit_TestCfg() {}

func (*TestUnit_HwTestCfg) isTestUnit_TestCfg() {}

func (*TestUnit_MoblabVmTestCfg) isTestUnit_TestCfg() {}

func (*TestUnit_TastVmTestCfg) isTestUnit_TestCfg() {}

func (*TestUnit_VmTestCfg) isTestUnit_TestCfg() {}

func (m *TestUnit) GetTestCfg() isTestUnit_TestCfg {
	if m != nil {
		return m.TestCfg
	}
	return nil
}

func (m *TestUnit) GetGceTestCfg() *GceTestCfg {
	if x, ok := m.GetTestCfg().(*TestUnit_GceTestCfg); ok {
		return x.GceTestCfg
	}
	return nil
}

func (m *TestUnit) GetHwTestCfg() *HwTestCfg {
	if x, ok := m.GetTestCfg().(*TestUnit_HwTestCfg); ok {
		return x.HwTestCfg
	}
	return nil
}

func (m *TestUnit) GetMoblabVmTestCfg() *MoblabVmTestCfg {
	if x, ok := m.GetTestCfg().(*TestUnit_MoblabVmTestCfg); ok {
		return x.MoblabVmTestCfg
	}
	return nil
}

func (m *TestUnit) GetTastVmTestCfg() *TastVmTestCfg {
	if x, ok := m.GetTestCfg().(*TestUnit_TastVmTestCfg); ok {
		return x.TastVmTestCfg
	}
	return nil
}

func (m *TestUnit) GetVmTestCfg() *VmTestCfg {
	if x, ok := m.GetTestCfg().(*TestUnit_VmTestCfg); ok {
		return x.VmTestCfg
	}
	return nil
}

func (m *TestUnit) GetSchedulingRequirements() *SchedulingRequirements {
	if m != nil {
		return m.SchedulingRequirements
	}
	return nil
}

func (m *TestUnit) GetBuildPayload() *BuildPayload {
	if m != nil {
		return m.BuildPayload
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TestUnit) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TestUnit_GceTestCfg)(nil),
		(*TestUnit_HwTestCfg)(nil),
		(*TestUnit_MoblabVmTestCfg)(nil),
		(*TestUnit_TastVmTestCfg)(nil),
		(*TestUnit_VmTestCfg)(nil),
	}
}

func init() {
	proto.RegisterType((*ProtoBytes)(nil), "testplans.ProtoBytes")
	proto.RegisterType((*GenerateTestPlanRequest)(nil), "testplans.GenerateTestPlanRequest")
	proto.RegisterType((*GenerateTestPlanResponse)(nil), "testplans.GenerateTestPlanResponse")
	proto.RegisterType((*BuildPayload)(nil), "testplans.BuildPayload")
	proto.RegisterType((*SchedulingRequirements)(nil), "testplans.SchedulingRequirements")
	proto.RegisterType((*TestUnit)(nil), "testplans.TestUnit")
}

func init() { proto.RegisterFile("testplans/generate_test_plan.proto", fileDescriptor_e8083f85c67203f6) }

var fileDescriptor_e8083f85c67203f6 = []byte{
	// 620 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4d, 0x4f, 0xdb, 0x40,
	0x10, 0xe5, 0x1b, 0x32, 0x09, 0x05, 0x16, 0x4a, 0x2c, 0xa4, 0x4a, 0x34, 0xed, 0x81, 0xf6, 0x90,
	0x54, 0x20, 0xfa, 0x21, 0xf5, 0xd2, 0xa4, 0x12, 0x54, 0x6a, 0xa5, 0xc8, 0x4d, 0x7b, 0xe0, 0xb2,
	0xda, 0x38, 0x1b, 0xdb, 0xc5, 0xf6, 0x9a, 0xdd, 0x31, 0x88, 0xfe, 0xb3, 0xfe, 0xa5, 0xfe, 0x8a,
	0xca, 0xb3, 0x4e, 0xbc, 0x11, 0xf4, 0x96, 0x7d, 0xf3, 0xde, 0xf3, 0x9b, 0x99, 0xdd, 0x40, 0x07,
	0xa5, 0xc1, 0x3c, 0x11, 0x99, 0xe9, 0x85, 0x32, 0x93, 0x5a, 0xa0, 0xe4, 0x25, 0xc4, 0x4b, 0xac,
	0x9b, 0x6b, 0x85, 0x8a, 0x35, 0xe6, 0x9c, 0xa3, 0x5e, 0x4d, 0x47, 0xa1, 0x43, 0x89, 0x96, 0xac,
	0xe5, 0x4d, 0x11, 0x6b, 0x99, 0xca, 0x0c, 0x0d, 0x0f, 0x54, 0x36, 0x8d, 0x43, 0xab, 0xed, 0xbc,
	0x03, 0x18, 0x96, 0x3f, 0xfa, 0xf7, 0x28, 0x0d, 0x7b, 0x05, 0xbb, 0x46, 0xea, 0x58, 0x24, 0xf1,
	0x6f, 0x39, 0xe1, 0xc4, 0xf0, 0x96, 0x8f, 0x97, 0x4f, 0x5a, 0xfe, 0x4e, 0x8d, 0x13, 0xbf, 0xf3,
	0x67, 0x05, 0xda, 0x17, 0x55, 0xa2, 0x91, 0x34, 0x38, 0x4c, 0x44, 0xe6, 0xcb, 0x9b, 0x42, 0x1a,
	0x64, 0xe7, 0xd0, 0x36, 0xaa, 0xd0, 0x81, 0xe4, 0xa8, 0xa5, 0xac, 0x3e, 0xc8, 0x73, 0x81, 0x11,
	0xb9, 0x35, 0xfc, 0x03, 0x5b, 0x1e, 0x69, 0x29, 0x07, 0x54, 0x1c, 0x0a, 0x8c, 0xd8, 0x27, 0x78,
	0xf6, 0xdf, 0xd0, 0x24, 0x5e, 0x21, 0xf1, 0x91, 0x25, 0x95, 0x1f, 0xf5, 0x1d, 0x0a, 0x59, 0x7c,
	0x06, 0x36, 0x2e, 0xe2, 0x64, 0x32, 0x2e, 0x82, 0x6b, 0x89, 0xb6, 0x03, 0xe3, 0xad, 0x1f, 0xaf,
	0x9e, 0x34, 0x4f, 0x9f, 0x76, 0xe7, 0xc3, 0xe9, 0xd6, 0x3d, 0xfb, 0x7b, 0x8e, 0x80, 0x60, 0xc3,
	0xde, 0x83, 0x17, 0x44, 0x5a, 0xa5, 0x71, 0x91, 0x2a, 0xc3, 0x83, 0x48, 0x06, 0xd7, 0xaa, 0x40,
	0xae, 0x95, 0x42, 0x6f, 0x8d, 0x32, 0x1c, 0xd6, 0xf5, 0x41, 0x55, 0xf6, 0x95, 0x42, 0xf6, 0x12,
	0x9e, 0x68, 0x99, 0x2b, 0x8e, 0x4a, 0x25, 0x36, 0xf3, 0x06, 0xf1, 0x5b, 0x25, 0x3a, 0x52, 0x2a,
	0x29, 0x53, 0x76, 0xbe, 0x82, 0xf7, 0x70, 0x74, 0x26, 0x57, 0x99, 0x91, 0xec, 0x0d, 0xd0, 0x3a,
	0x79, 0x91, 0xc5, 0xe8, 0x2d, 0x53, 0xf0, 0x7d, 0x27, 0x78, 0xc9, 0xff, 0x91, 0xc5, 0xe8, 0x6f,
	0x61, 0xf5, 0xab, 0xf3, 0x0b, 0x5a, 0xfd, 0xb2, 0x85, 0xa1, 0xb8, 0x4f, 0x94, 0x98, 0xb0, 0x2e,
	0xec, 0x0b, 0x8d, 0xf1, 0x54, 0x04, 0x68, 0x78, 0x68, 0xb8, 0x6d, 0xad, 0x9a, 0xfc, 0xde, 0xbc,
	0x74, 0x61, 0xfa, 0x54, 0x60, 0xaf, 0x61, 0x6f, 0x81, 0xef, 0x8c, 0x7a, 0xc7, 0x61, 0x57, 0xc9,
	0x0f, 0xbf, 0x07, 0x91, 0x9c, 0x14, 0x49, 0x9c, 0x85, 0xee, 0xf4, 0xd9, 0x0b, 0x68, 0xd1, 0x20,
	0xb9, 0xdd, 0x8e, 0x35, 0xb8, 0x5c, 0xf2, 0x9b, 0x84, 0x8e, 0x08, 0xec, 0x6f, 0x43, 0x73, 0xb6,
	0xe1, 0xfb, 0x5c, 0x76, 0xfe, 0xae, 0xc2, 0xd6, 0xac, 0x21, 0xf6, 0x01, 0x5a, 0x61, 0x50, 0x5d,
	0xee, 0x60, 0x1a, 0x52, 0xde, 0xc5, 0xa5, 0x5d, 0x04, 0x34, 0xae, 0xc1, 0x34, 0xbc, 0x5c, 0xf2,
	0x21, 0x9c, 0x9f, 0xd8, 0x5b, 0x68, 0x46, 0x77, 0xb5, 0x72, 0x85, 0x94, 0x07, 0x8e, 0xf2, 0xf2,
	0xae, 0x16, 0x36, 0xa2, 0xd9, 0x81, 0x7d, 0x01, 0x96, 0xaa, 0x71, 0x22, 0xc6, 0xfc, 0x36, 0xad,
	0xe5, 0xab, 0x24, 0x3f, 0x72, 0xe4, 0xdf, 0x88, 0xf4, 0x33, 0xad, 0x4d, 0x76, 0xd2, 0x45, 0x88,
	0x0d, 0x60, 0x17, 0x85, 0xc1, 0x05, 0xa3, 0x35, 0x32, 0xf2, 0xdc, 0xed, 0x09, 0x83, 0xae, 0xcd,
	0x36, 0xba, 0x40, 0xd9, 0x87, 0xab, 0x5f, 0x7f, 0xd0, 0x87, 0xab, 0x6d, 0xdc, 0xce, 0x75, 0x57,
	0xd0, 0x36, 0xf3, 0xad, 0x2c, 0xbc, 0x1b, 0xba, 0x7e, 0xcd, 0xd3, 0xe7, 0x8e, 0xc7, 0xe3, 0xfb,
	0xf3, 0x0f, 0xcd, 0xe3, 0x7b, 0xfd, 0x08, 0xdb, 0x76, 0xaf, 0xb9, 0xbd, 0x5e, 0xde, 0x26, 0x39,
	0xb6, 0x1d, 0x47, 0xf7, 0xf6, 0xf9, 0xf6, 0x16, 0x54, 0xa7, 0x7e, 0x03, 0x36, 0xab, 0x90, 0xfd,
	0xf3, 0xab, 0xb3, 0x50, 0x75, 0x67, 0xef, 0xa6, 0xab, 0x74, 0xd8, 0xab, 0x1f, 0x51, 0x2f, 0xce,
	0xa6, 0x5a, 0xf4, 0xe8, 0xbd, 0xf6, 0x42, 0x55, 0xff, 0x8d, 0x8d, 0x37, 0x08, 0x3b, 0xfb, 0x17,
	0x00, 0x00, 0xff, 0xff, 0x3c, 0x5f, 0x1a, 0x70, 0x09, 0x05, 0x00, 0x00,
}
