// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testplans/pointless_build.proto

package testplans

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	api "go.chromium.org/chromiumos/infra/proto/go/chromite/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PointlessBuildCheckResponse_PointlessBuildReason int32

const (
	PointlessBuildCheckResponse_POINTLESS_BUILD_REASON_UNSPECIFIED          PointlessBuildCheckResponse_PointlessBuildReason = 0
	PointlessBuildCheckResponse_IRRELEVANT_TO_DEPS_GRAPH                    PointlessBuildCheckResponse_PointlessBuildReason = 1
	PointlessBuildCheckResponse_IRRELEVANT_TO_KNOWN_NON_PORTAGE_DIRECTORIES PointlessBuildCheckResponse_PointlessBuildReason = 2
)

var PointlessBuildCheckResponse_PointlessBuildReason_name = map[int32]string{
	0: "POINTLESS_BUILD_REASON_UNSPECIFIED",
	1: "IRRELEVANT_TO_DEPS_GRAPH",
	2: "IRRELEVANT_TO_KNOWN_NON_PORTAGE_DIRECTORIES",
}

var PointlessBuildCheckResponse_PointlessBuildReason_value = map[string]int32{
	"POINTLESS_BUILD_REASON_UNSPECIFIED":          0,
	"IRRELEVANT_TO_DEPS_GRAPH":                    1,
	"IRRELEVANT_TO_KNOWN_NON_PORTAGE_DIRECTORIES": 2,
}

func (x PointlessBuildCheckResponse_PointlessBuildReason) String() string {
	return proto.EnumName(PointlessBuildCheckResponse_PointlessBuildReason_name, int32(x))
}

func (PointlessBuildCheckResponse_PointlessBuildReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65492a4cea7c5e67, []int{1, 0}
}

// The input proto for invocations of the Pointless Build Checker program.
type PointlessBuildCheckRequest struct {
	// Serialized buildbucket Build proto for this child builder run.
	// See https://chromium.googlesource.com/infra/luci/luci-go/+/master/buildbucket/proto/build.proto
	BuildbucketProto *ProtoBytes `protobuf:"bytes,1,opt,name=buildbucket_proto,json=buildbucketProto,proto3" json:"buildbucket_proto,omitempty"`
	// The DepGraph for this child builder.
	DepGraph *api.DepGraph `protobuf:"bytes,5,opt,name=dep_graph,json=depGraph,proto3" json:"dep_graph,omitempty"`
	// Path on disk to the chromiumos workspace repo checkout.
	ChromiumosWorkspaceCheckoutRoot string `protobuf:"bytes,3,opt,name=chromiumos_workspace_checkout_root,json=chromiumosWorkspaceCheckoutRoot,proto3" json:"chromiumos_workspace_checkout_root,omitempty"`
	// Path on disk to the "repo" CLI tool.
	RepoToolPath         string   `protobuf:"bytes,4,opt,name=repo_tool_path,json=repoToolPath,proto3" json:"repo_tool_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointlessBuildCheckRequest) Reset()         { *m = PointlessBuildCheckRequest{} }
func (m *PointlessBuildCheckRequest) String() string { return proto.CompactTextString(m) }
func (*PointlessBuildCheckRequest) ProtoMessage()    {}
func (*PointlessBuildCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65492a4cea7c5e67, []int{0}
}

func (m *PointlessBuildCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointlessBuildCheckRequest.Unmarshal(m, b)
}
func (m *PointlessBuildCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointlessBuildCheckRequest.Marshal(b, m, deterministic)
}
func (m *PointlessBuildCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointlessBuildCheckRequest.Merge(m, src)
}
func (m *PointlessBuildCheckRequest) XXX_Size() int {
	return xxx_messageInfo_PointlessBuildCheckRequest.Size(m)
}
func (m *PointlessBuildCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PointlessBuildCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PointlessBuildCheckRequest proto.InternalMessageInfo

func (m *PointlessBuildCheckRequest) GetBuildbucketProto() *ProtoBytes {
	if m != nil {
		return m.BuildbucketProto
	}
	return nil
}

func (m *PointlessBuildCheckRequest) GetDepGraph() *api.DepGraph {
	if m != nil {
		return m.DepGraph
	}
	return nil
}

func (m *PointlessBuildCheckRequest) GetChromiumosWorkspaceCheckoutRoot() string {
	if m != nil {
		return m.ChromiumosWorkspaceCheckoutRoot
	}
	return ""
}

func (m *PointlessBuildCheckRequest) GetRepoToolPath() string {
	if m != nil {
		return m.RepoToolPath
	}
	return ""
}

// The output proto for invocations of the Pointless Build Checker program.
type PointlessBuildCheckResponse struct {
	// Whether the build is pointless and can be terminated without proceeding to
	// building packages and testing.
	BuildIsPointless *wrappers.BoolValue `protobuf:"bytes,1,opt,name=build_is_pointless,json=buildIsPointless,proto3" json:"build_is_pointless,omitempty"`
	// If build_is_pointless, this is the reason that the Pointless Build Checker
	// came to that conclusion. Otherwise, this is unspecified.
	PointlessBuildReason PointlessBuildCheckResponse_PointlessBuildReason `protobuf:"varint,2,opt,name=pointless_build_reason,json=pointlessBuildReason,proto3,enum=testplans.PointlessBuildCheckResponse_PointlessBuildReason" json:"pointless_build_reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *PointlessBuildCheckResponse) Reset()         { *m = PointlessBuildCheckResponse{} }
func (m *PointlessBuildCheckResponse) String() string { return proto.CompactTextString(m) }
func (*PointlessBuildCheckResponse) ProtoMessage()    {}
func (*PointlessBuildCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65492a4cea7c5e67, []int{1}
}

func (m *PointlessBuildCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointlessBuildCheckResponse.Unmarshal(m, b)
}
func (m *PointlessBuildCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointlessBuildCheckResponse.Marshal(b, m, deterministic)
}
func (m *PointlessBuildCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointlessBuildCheckResponse.Merge(m, src)
}
func (m *PointlessBuildCheckResponse) XXX_Size() int {
	return xxx_messageInfo_PointlessBuildCheckResponse.Size(m)
}
func (m *PointlessBuildCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PointlessBuildCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PointlessBuildCheckResponse proto.InternalMessageInfo

func (m *PointlessBuildCheckResponse) GetBuildIsPointless() *wrappers.BoolValue {
	if m != nil {
		return m.BuildIsPointless
	}
	return nil
}

func (m *PointlessBuildCheckResponse) GetPointlessBuildReason() PointlessBuildCheckResponse_PointlessBuildReason {
	if m != nil {
		return m.PointlessBuildReason
	}
	return PointlessBuildCheckResponse_POINTLESS_BUILD_REASON_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("testplans.PointlessBuildCheckResponse_PointlessBuildReason", PointlessBuildCheckResponse_PointlessBuildReason_name, PointlessBuildCheckResponse_PointlessBuildReason_value)
	proto.RegisterType((*PointlessBuildCheckRequest)(nil), "testplans.PointlessBuildCheckRequest")
	proto.RegisterType((*PointlessBuildCheckResponse)(nil), "testplans.PointlessBuildCheckResponse")
}

func init() { proto.RegisterFile("testplans/pointless_build.proto", fileDescriptor_65492a4cea7c5e67) }

var fileDescriptor_65492a4cea7c5e67 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdd, 0x6a, 0xdb, 0x30,
	0x14, 0xc7, 0xe7, 0xec, 0x83, 0x45, 0x1b, 0x25, 0x13, 0x5d, 0x30, 0xe9, 0x58, 0x43, 0x18, 0x23,
	0x30, 0x90, 0xa1, 0x61, 0x57, 0xbb, 0x8a, 0x13, 0x2f, 0x35, 0x0d, 0xb6, 0x91, 0xdd, 0x16, 0x76,
	0x23, 0x14, 0x47, 0x75, 0x4c, 0x1c, 0x1f, 0x55, 0x92, 0x29, 0x7b, 0x83, 0xdd, 0xec, 0x45, 0xf7,
	0x14, 0x23, 0xce, 0x57, 0x57, 0xb2, 0x3b, 0xfb, 0x7f, 0x7e, 0xe7, 0xeb, 0x7f, 0x84, 0xce, 0x8d,
	0xd0, 0x46, 0x16, 0xbc, 0xd4, 0x8e, 0x84, 0xbc, 0x34, 0x85, 0xd0, 0x9a, 0xcd, 0xaa, 0xbc, 0x98,
	0x13, 0xa9, 0xc0, 0x00, 0x6e, 0xee, 0x81, 0xce, 0x59, 0xba, 0x50, 0xb0, 0xca, 0x8d, 0x70, 0xb8,
	0xcc, 0x9d, 0xb9, 0x90, 0x99, 0xe2, 0x72, 0xb1, 0xe1, 0x3a, 0xed, 0x43, 0xa1, 0x14, 0x56, 0x2b,
	0x28, 0xb7, 0xfa, 0xc7, 0x0c, 0x20, 0x2b, 0x84, 0x53, 0xff, 0xcd, 0xaa, 0x3b, 0xe7, 0x41, 0x71,
	0x29, 0x85, 0xd2, 0x9b, 0x78, 0xef, 0x57, 0x03, 0x75, 0xa2, 0x5d, 0x67, 0x77, 0xdd, 0x78, 0xb4,
	0x10, 0xe9, 0x92, 0x8a, 0xfb, 0x4a, 0x68, 0x83, 0x5d, 0xf4, 0xae, 0x9e, 0x66, 0x56, 0xa5, 0x4b,
	0x61, 0x58, 0x9d, 0x63, 0x5b, 0x5d, 0xab, 0xff, 0xe6, 0xe2, 0x3d, 0xd9, 0xb7, 0x24, 0xd1, 0x5a,
	0x77, 0x7f, 0x1a, 0xa1, 0x69, 0xeb, 0x11, 0x5f, 0xcb, 0x78, 0x80, 0x9a, 0x73, 0x21, 0x59, 0x3d,
	0xad, 0xfd, 0xb2, 0xce, 0x6d, 0x93, 0xdd, 0x2e, 0x84, 0xcb, 0x9c, 0x8c, 0x85, 0x9c, 0xac, 0xa3,
	0xf4, 0xf5, 0x7c, 0xfb, 0x85, 0xaf, 0x50, 0x6f, 0x83, 0x54, 0x2b, 0xd0, 0xec, 0x01, 0xd4, 0x52,
	0x4b, 0x9e, 0x0a, 0x96, 0xae, 0xa7, 0x83, 0xca, 0x30, 0x05, 0x60, 0xec, 0xe7, 0x5d, 0xab, 0xdf,
	0xa4, 0xe7, 0x07, 0xf2, 0x76, 0x07, 0x8e, 0xb6, 0x1c, 0x05, 0x30, 0xf8, 0x13, 0x3a, 0x51, 0x42,
	0x02, 0x33, 0x00, 0x05, 0x93, 0xdc, 0x2c, 0xec, 0x17, 0x75, 0xe2, 0xdb, 0xb5, 0x9a, 0x00, 0x14,
	0x11, 0x37, 0x8b, 0xde, 0x9f, 0x06, 0x3a, 0x3b, 0x6a, 0x85, 0x96, 0x50, 0x6a, 0x81, 0x2f, 0x11,
	0xae, 0x77, 0x63, 0xb9, 0x66, 0xfb, 0x63, 0x6d, 0xcd, 0xe8, 0x90, 0x8d, 0xcf, 0x64, 0xe7, 0x33,
	0x71, 0x01, 0x8a, 0x1b, 0x5e, 0x54, 0x62, 0xeb, 0x88, 0xaf, 0xf7, 0xb5, 0xf1, 0x3d, 0x6a, 0x3f,
	0xb9, 0x36, 0x53, 0x82, 0x6b, 0x28, 0xed, 0x46, 0xd7, 0xea, 0x9f, 0x5c, 0x7c, 0x7b, 0x6c, 0xed,
	0xff, 0x27, 0x7a, 0x12, 0xa3, 0x75, 0x09, 0x7a, 0x2a, 0x8f, 0xa8, 0xbd, 0xdf, 0x16, 0x3a, 0x3d,
	0x86, 0xe3, 0xcf, 0xa8, 0x17, 0x85, 0x7e, 0x90, 0x4c, 0xbd, 0x38, 0x66, 0xee, 0xb5, 0x3f, 0x1d,
	0x33, 0xea, 0x0d, 0xe3, 0x30, 0x60, 0xd7, 0x41, 0x1c, 0x79, 0x23, 0xff, 0xbb, 0xef, 0x8d, 0x5b,
	0xcf, 0xf0, 0x07, 0x64, 0xfb, 0x94, 0x7a, 0x53, 0xef, 0x66, 0x18, 0x24, 0x2c, 0x09, 0xd9, 0xd8,
	0x8b, 0x62, 0x36, 0xa1, 0xc3, 0xe8, 0xb2, 0x65, 0x61, 0x07, 0x7d, 0xf9, 0x37, 0x7a, 0x15, 0x84,
	0xb7, 0x01, 0x0b, 0xc2, 0x80, 0x45, 0x21, 0x4d, 0x86, 0x13, 0x8f, 0x8d, 0x7d, 0xea, 0x8d, 0x92,
	0x90, 0xfa, 0x5e, 0xdc, 0x6a, 0xb8, 0x5f, 0x7f, 0x0c, 0x32, 0x20, 0xbb, 0xc3, 0x11, 0x50, 0x99,
	0x73, 0xb8, 0xa2, 0x93, 0x97, 0x77, 0x8a, 0x6f, 0xde, 0xac, 0x93, 0x81, 0xb3, 0x77, 0x63, 0xf6,
	0xaa, 0xd6, 0x06, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x55, 0x2e, 0x78, 0xe7, 0x38, 0x03, 0x00,
	0x00,
}
