// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testplans/source_tree_test_config.proto

package testplans

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Testing restrictions to apply to a source tree.
type TestRestriction struct {
	// Whether to disable hardware tests.
	DisableHwTests bool `protobuf:"varint,1,opt,name=disable_hw_tests,json=disableHwTests,proto3" json:"disable_hw_tests,omitempty"`
	// Whether to disable image tests.
	DisableImageTests bool `protobuf:"varint,2,opt,name=disable_image_tests,json=disableImageTests,proto3" json:"disable_image_tests,omitempty"`
	// Whether to disable virtual machine tests.
	DisableVmTests       bool     `protobuf:"varint,3,opt,name=disable_vm_tests,json=disableVmTests,proto3" json:"disable_vm_tests,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRestriction) Reset()         { *m = TestRestriction{} }
func (m *TestRestriction) String() string { return proto.CompactTextString(m) }
func (*TestRestriction) ProtoMessage()    {}
func (*TestRestriction) Descriptor() ([]byte, []int) {
	return fileDescriptor_9aed450ade7161bc, []int{0}
}

func (m *TestRestriction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRestriction.Unmarshal(m, b)
}
func (m *TestRestriction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRestriction.Marshal(b, m, deterministic)
}
func (m *TestRestriction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRestriction.Merge(m, src)
}
func (m *TestRestriction) XXX_Size() int {
	return xxx_messageInfo_TestRestriction.Size(m)
}
func (m *TestRestriction) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRestriction.DiscardUnknown(m)
}

var xxx_messageInfo_TestRestriction proto.InternalMessageInfo

func (m *TestRestriction) GetDisableHwTests() bool {
	if m != nil {
		return m.DisableHwTests
	}
	return false
}

func (m *TestRestriction) GetDisableImageTests() bool {
	if m != nil {
		return m.DisableImageTests
	}
	return false
}

func (m *TestRestriction) GetDisableVmTests() bool {
	if m != nil {
		return m.DisableVmTests
	}
	return false
}

// A unit of the CrOS codebase. As of 2019-01, this concept maps 1-to-1 with
// "paths" in the the internal and external full.xml files.
type SourceTree struct {
	// The path of a source tree,
	// e.g. "src/platform2" or "src/third_party/kernel/v4.19".
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceTree) Reset()         { *m = SourceTree{} }
func (m *SourceTree) String() string { return proto.CompactTextString(m) }
func (*SourceTree) ProtoMessage()    {}
func (*SourceTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_9aed450ade7161bc, []int{1}
}

func (m *SourceTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceTree.Unmarshal(m, b)
}
func (m *SourceTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceTree.Marshal(b, m, deterministic)
}
func (m *SourceTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceTree.Merge(m, src)
}
func (m *SourceTree) XXX_Size() int {
	return xxx_messageInfo_SourceTree.Size(m)
}
func (m *SourceTree) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceTree.DiscardUnknown(m)
}

var xxx_messageInfo_SourceTree proto.InternalMessageInfo

func (m *SourceTree) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// A set of test restrictions for a source tree.
type SourceTreeTestRestriction struct {
	// A CrOS source tree.
	SourceTree *SourceTree `protobuf:"bytes,1,opt,name=source_tree,json=sourceTree,proto3" json:"source_tree,omitempty"`
	// The test restrictions to apply to the source tree.
	TestRestriction      *TestRestriction `protobuf:"bytes,2,opt,name=test_restriction,json=testRestriction,proto3" json:"test_restriction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SourceTreeTestRestriction) Reset()         { *m = SourceTreeTestRestriction{} }
func (m *SourceTreeTestRestriction) String() string { return proto.CompactTextString(m) }
func (*SourceTreeTestRestriction) ProtoMessage()    {}
func (*SourceTreeTestRestriction) Descriptor() ([]byte, []int) {
	return fileDescriptor_9aed450ade7161bc, []int{2}
}

func (m *SourceTreeTestRestriction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceTreeTestRestriction.Unmarshal(m, b)
}
func (m *SourceTreeTestRestriction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceTreeTestRestriction.Marshal(b, m, deterministic)
}
func (m *SourceTreeTestRestriction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceTreeTestRestriction.Merge(m, src)
}
func (m *SourceTreeTestRestriction) XXX_Size() int {
	return xxx_messageInfo_SourceTreeTestRestriction.Size(m)
}
func (m *SourceTreeTestRestriction) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceTreeTestRestriction.DiscardUnknown(m)
}

var xxx_messageInfo_SourceTreeTestRestriction proto.InternalMessageInfo

func (m *SourceTreeTestRestriction) GetSourceTree() *SourceTree {
	if m != nil {
		return m.SourceTree
	}
	return nil
}

func (m *SourceTreeTestRestriction) GetTestRestriction() *TestRestriction {
	if m != nil {
		return m.TestRestriction
	}
	return nil
}

// Configures test restrictions for all relevant source trees.
// This is the root message.
type SourceTreeTestCfg struct {
	// (Source tree, test restriction) pairs.
	SourceTreeTestRestriction []*SourceTreeTestRestriction `protobuf:"bytes,1,rep,name=source_tree_test_restriction,json=sourceTreeTestRestriction,proto3" json:"source_tree_test_restriction,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                     `json:"-"`
	XXX_unrecognized          []byte                       `json:"-"`
	XXX_sizecache             int32                        `json:"-"`
}

func (m *SourceTreeTestCfg) Reset()         { *m = SourceTreeTestCfg{} }
func (m *SourceTreeTestCfg) String() string { return proto.CompactTextString(m) }
func (*SourceTreeTestCfg) ProtoMessage()    {}
func (*SourceTreeTestCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9aed450ade7161bc, []int{3}
}

func (m *SourceTreeTestCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceTreeTestCfg.Unmarshal(m, b)
}
func (m *SourceTreeTestCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceTreeTestCfg.Marshal(b, m, deterministic)
}
func (m *SourceTreeTestCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceTreeTestCfg.Merge(m, src)
}
func (m *SourceTreeTestCfg) XXX_Size() int {
	return xxx_messageInfo_SourceTreeTestCfg.Size(m)
}
func (m *SourceTreeTestCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceTreeTestCfg.DiscardUnknown(m)
}

var xxx_messageInfo_SourceTreeTestCfg proto.InternalMessageInfo

func (m *SourceTreeTestCfg) GetSourceTreeTestRestriction() []*SourceTreeTestRestriction {
	if m != nil {
		return m.SourceTreeTestRestriction
	}
	return nil
}

func init() {
	proto.RegisterType((*TestRestriction)(nil), "testplans.TestRestriction")
	proto.RegisterType((*SourceTree)(nil), "testplans.SourceTree")
	proto.RegisterType((*SourceTreeTestRestriction)(nil), "testplans.SourceTreeTestRestriction")
	proto.RegisterType((*SourceTreeTestCfg)(nil), "testplans.SourceTreeTestCfg")
}

func init() {
	proto.RegisterFile("testplans/source_tree_test_config.proto", fileDescriptor_9aed450ade7161bc)
}

var fileDescriptor_9aed450ade7161bc = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x89, 0x15, 0xb1, 0x13, 0xb0, 0xed, 0x8a, 0x60, 0xc5, 0x43, 0x09, 0x82, 0x39, 0xed,
	0x42, 0x8a, 0x3e, 0x80, 0x22, 0xe8, 0x35, 0x16, 0x0f, 0x5e, 0x42, 0x1a, 0x37, 0x9b, 0x85, 0x26,
	0x1b, 0x76, 0xb7, 0x16, 0x7c, 0x0f, 0x2f, 0x3e, 0xad, 0x64, 0x4c, 0xf3, 0x4f, 0xbd, 0x25, 0x33,
	0xbf, 0x6f, 0xbe, 0xf9, 0x26, 0x81, 0x6b, 0xcb, 0x8d, 0x2d, 0x37, 0x71, 0x61, 0x98, 0x51, 0x5b,
	0x9d, 0xf0, 0xc8, 0x6a, 0xce, 0xa3, 0xaa, 0x1a, 0x25, 0xaa, 0x48, 0xa5, 0xa0, 0xa5, 0x56, 0x56,
	0x91, 0x71, 0x03, 0x7a, 0x9f, 0x0e, 0x4c, 0x56, 0xdc, 0xd8, 0x90, 0x1b, 0xab, 0x65, 0x62, 0xa5,
	0x2a, 0x88, 0x0f, 0xd3, 0x37, 0x69, 0xe2, 0xf5, 0x86, 0x47, 0xd9, 0x0e, 0xe5, 0xe6, 0xdc, 0x59,
	0x38, 0xfe, 0x71, 0x78, 0x52, 0xd7, 0x1f, 0x77, 0x95, 0xc6, 0x10, 0x0a, 0xa7, 0x7b, 0x52, 0xe6,
	0xb1, 0xe0, 0x35, 0x7c, 0x80, 0xf0, 0xac, 0x6e, 0x3d, 0x55, 0x9d, 0x1f, 0xbe, 0x33, 0xf9, 0x3d,
	0xaf, 0xe1, 0x51, 0x6f, 0xf2, 0x4b, 0x8e, 0xa4, 0xb7, 0x00, 0x78, 0xc6, 0x0c, 0x2b, 0xcd, 0x39,
	0x21, 0x70, 0x58, 0xc6, 0x36, 0xc3, 0x2d, 0xc6, 0x21, 0x3e, 0x7b, 0x5f, 0x0e, 0xcc, 0x5b, 0x64,
	0x98, 0xe1, 0x16, 0xdc, 0xce, 0x0d, 0x50, 0xe8, 0x06, 0x67, 0xb4, 0x09, 0x4e, 0x5b, 0x69, 0x08,
	0xa6, 0x75, 0x7a, 0x80, 0x29, 0xde, 0x4b, 0xb7, 0xb3, 0x30, 0x8e, 0x1b, 0x5c, 0x74, 0xc4, 0x03,
	0xb7, 0x70, 0x62, 0xfb, 0x05, 0xef, 0x03, 0x66, 0xfd, 0xdd, 0xee, 0x53, 0x41, 0x38, 0x5c, 0xfe,
	0xfa, 0x2e, 0x5d, 0x1f, 0x67, 0x31, 0xf2, 0xdd, 0xe0, 0xea, 0xcf, 0x25, 0x87, 0x8e, 0x73, 0xf3,
	0x5f, 0xeb, 0xee, 0xe6, 0x75, 0x29, 0x14, 0x4d, 0x32, 0xad, 0x72, 0xb9, 0xcd, 0xa9, 0xd2, 0x82,
	0xed, 0x5f, 0x94, 0x61, 0xb2, 0x48, 0x75, 0xcc, 0xf0, 0x3f, 0x60, 0x42, 0xb1, 0xc6, 0x6b, 0x7d,
	0x84, 0xb5, 0xe5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xea, 0x5f, 0xb2, 0x46, 0x02, 0x00,
	0x00,
}
