// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromite/api/android.proto

package chromite_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "go.chromium.org/chromiumos/infra/proto/go/chromite/api"
	chromiumos "go.chromium.org/chromiumos/infra/proto/go/chromiumos"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MarkStableRequest struct {
	// Required.
	// The manifest branch being used.
	TrackingBranch string `protobuf:"bytes,1,opt,name=tracking_branch,json=trackingBranch,proto3" json:"tracking_branch,omitempty"`
	// Required.
	// Portage package name for Android container.
	Package string `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	// Required.
	// Android branch to import from.
	AndroidBuildBranch string `protobuf:"bytes,3,opt,name=android_build_branch,json=androidBuildBranch,proto3" json:"android_build_branch,omitempty"`
	// Force set the android build id that will be used.
	AndroidVersion string `protobuf:"bytes,4,opt,name=android_version,json=androidVersion,proto3" json:"android_version,omitempty"`
	// Android GTS branch to copy artifacts from.
	AndroidGtsBuildBranch string `protobuf:"bytes,5,opt,name=android_gts_build_branch,json=androidGtsBuildBranch,proto3" json:"android_gts_build_branch,omitempty"`
	// The set of relevant build targets. Used to clean old version and for a
	// emerge-able sanity check for the new version.
	Boards               []*chromiumos.BuildTarget `protobuf:"bytes,6,rep,name=boards,proto3" json:"boards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MarkStableRequest) Reset()         { *m = MarkStableRequest{} }
func (m *MarkStableRequest) String() string { return proto.CompactTextString(m) }
func (*MarkStableRequest) ProtoMessage()    {}
func (*MarkStableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f74c095a284c1bd1, []int{0}
}

func (m *MarkStableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkStableRequest.Unmarshal(m, b)
}
func (m *MarkStableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkStableRequest.Marshal(b, m, deterministic)
}
func (m *MarkStableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkStableRequest.Merge(m, src)
}
func (m *MarkStableRequest) XXX_Size() int {
	return xxx_messageInfo_MarkStableRequest.Size(m)
}
func (m *MarkStableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkStableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarkStableRequest proto.InternalMessageInfo

func (m *MarkStableRequest) GetTrackingBranch() string {
	if m != nil {
		return m.TrackingBranch
	}
	return ""
}

func (m *MarkStableRequest) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *MarkStableRequest) GetAndroidBuildBranch() string {
	if m != nil {
		return m.AndroidBuildBranch
	}
	return ""
}

func (m *MarkStableRequest) GetAndroidVersion() string {
	if m != nil {
		return m.AndroidVersion
	}
	return ""
}

func (m *MarkStableRequest) GetAndroidGtsBuildBranch() string {
	if m != nil {
		return m.AndroidGtsBuildBranch
	}
	return ""
}

func (m *MarkStableRequest) GetBoards() []*chromiumos.BuildTarget {
	if m != nil {
		return m.Boards
	}
	return nil
}

type MarkStableResponse struct {
	// The new package atom.
	AndroidAtom          *chromiumos.PackageInfo `protobuf:"bytes,1,opt,name=android_atom,json=androidAtom,proto3" json:"android_atom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *MarkStableResponse) Reset()         { *m = MarkStableResponse{} }
func (m *MarkStableResponse) String() string { return proto.CompactTextString(m) }
func (*MarkStableResponse) ProtoMessage()    {}
func (*MarkStableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f74c095a284c1bd1, []int{1}
}

func (m *MarkStableResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkStableResponse.Unmarshal(m, b)
}
func (m *MarkStableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkStableResponse.Marshal(b, m, deterministic)
}
func (m *MarkStableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkStableResponse.Merge(m, src)
}
func (m *MarkStableResponse) XXX_Size() int {
	return xxx_messageInfo_MarkStableResponse.Size(m)
}
func (m *MarkStableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkStableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MarkStableResponse proto.InternalMessageInfo

func (m *MarkStableResponse) GetAndroidAtom() *chromiumos.PackageInfo {
	if m != nil {
		return m.AndroidAtom
	}
	return nil
}

func init() {
	proto.RegisterType((*MarkStableRequest)(nil), "chromite.api.MarkStableRequest")
	proto.RegisterType((*MarkStableResponse)(nil), "chromite.api.MarkStableResponse")
}

func init() { proto.RegisterFile("chromite/api/android.proto", fileDescriptor_f74c095a284c1bd1) }

var fileDescriptor_f74c095a284c1bd1 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4e, 0xf2, 0x40,
	0x14, 0x85, 0x03, 0xfc, 0x3f, 0xc4, 0x0b, 0x01, 0x9d, 0x68, 0x68, 0x1a, 0x13, 0x09, 0x1b, 0x58,
	0xb5, 0x06, 0x17, 0x26, 0xee, 0x60, 0x63, 0x5c, 0x18, 0x49, 0x31, 0x6e, 0xc9, 0x6d, 0x3b, 0x96,
	0x09, 0xb4, 0xb7, 0xce, 0x0c, 0xbc, 0x8c, 0x6f, 0xe3, 0xfb, 0xf8, 0x0e, 0xc6, 0x99, 0x69, 0x00,
	0x8d, 0xcb, 0xb9, 0xe7, 0x9b, 0x73, 0x6e, 0xce, 0x05, 0x3f, 0x59, 0x49, 0xca, 0x85, 0xe6, 0x21,
	0x96, 0x22, 0xc4, 0x22, 0x95, 0x24, 0xd2, 0xa0, 0x94, 0xa4, 0x89, 0x75, 0x2a, 0x2d, 0xc0, 0x52,
	0xf8, 0x97, 0x47, 0x64, 0xbc, 0x15, 0x9b, 0x74, 0x89, 0xa5, 0xb0, 0xac, 0xdf, 0xb7, 0xea, 0x36,
	0x27, 0x15, 0x26, 0x94, 0xe7, 0x54, 0x58, 0x61, 0xf8, 0x5e, 0x87, 0xb3, 0x47, 0x94, 0xeb, 0x85,
	0xc6, 0x78, 0xc3, 0x23, 0xfe, 0xb6, 0xe5, 0x4a, 0xb3, 0x11, 0xf4, 0xb4, 0xc4, 0x64, 0x2d, 0x8a,
	0x6c, 0x19, 0x4b, 0x2c, 0x92, 0x95, 0x57, 0x1b, 0xd4, 0xc6, 0x27, 0x51, 0xb7, 0x1a, 0xcf, 0xcc,
	0x94, 0x79, 0xd0, 0x2a, 0x31, 0x59, 0x63, 0xc6, 0xbd, 0xba, 0x01, 0xaa, 0x27, 0xbb, 0x86, 0x73,
	0xb7, 0xee, 0xd2, 0x2e, 0xe3, 0x7c, 0x1a, 0x06, 0x63, 0x4e, 0x9b, 0x7d, 0x4b, 0xce, 0x6b, 0x04,
	0xbd, 0xea, 0xc7, 0x8e, 0x4b, 0x25, 0xa8, 0xf0, 0xfe, 0xd9, 0x50, 0x37, 0x7e, 0xb1, 0x53, 0x76,
	0x0b, 0x5e, 0x05, 0x66, 0x5a, 0x1d, 0xdb, 0xff, 0x37, 0x3f, 0x2e, 0x9c, 0x7e, 0xaf, 0xd5, 0x61,
	0x42, 0x08, 0xcd, 0x98, 0x50, 0xa6, 0xca, 0x6b, 0x0e, 0x1a, 0xe3, 0xf6, 0xa4, 0x1f, 0xec, 0x6b,
	0x09, 0x0c, 0xf8, 0x8c, 0x32, 0xe3, 0x3a, 0x72, 0xd8, 0x70, 0x0e, 0xec, 0xb0, 0x1c, 0x55, 0x52,
	0xa1, 0x38, 0xbb, 0x83, 0x4e, 0x95, 0x8f, 0x9a, 0x72, 0x53, 0xcd, 0x0f, 0xb3, 0xb9, 0x6d, 0xe1,
	0xa1, 0x78, 0xa5, 0xa8, 0xed, 0xe0, 0xa9, 0xa6, 0x7c, 0x22, 0xa1, 0x3b, 0xb5, 0xcf, 0x05, 0x97,
	0x3b, 0x91, 0x70, 0xf6, 0x04, 0xb0, 0xcf, 0x60, 0x57, 0xc1, 0xe1, 0x55, 0x83, 0x5f, 0xa7, 0xf1,
	0x07, 0x7f, 0x03, 0x76, 0x3d, 0xbf, 0xf7, 0xf1, 0xe9, 0xb7, 0xa1, 0xe5, 0x52, 0x4f, 0x6b, 0x71,
	0xd3, 0x9c, 0xfa, 0xe6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x86, 0xb6, 0xaf, 0x79, 0x4d, 0x02, 0x00,
	0x00,
}
