// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromite/api/depgraph.proto

package chromite_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "go.chromium.org/chromiumos/infra/proto/go/chromite/api"
	chromiumos "go.chromium.org/chromiumos/infra/proto/go/chromiumos"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message contains data about the portage dependency graph and the packages'
// dependency source paths.
type DepGraph struct {
	// The board whose dependency graph is being created for.
	BuildTarget *chromiumos.BuildTarget `protobuf:"bytes,1,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	// List of packages in the dependency graph and their infos, which include
	// dependency packages and the source paths.
	PackageDeps          []*PackageDepInfo `protobuf:"bytes,2,rep,name=package_deps,json=packageDeps,proto3" json:"package_deps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DepGraph) Reset()         { *m = DepGraph{} }
func (m *DepGraph) String() string { return proto.CompactTextString(m) }
func (*DepGraph) ProtoMessage()    {}
func (*DepGraph) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a5308b238ddba97, []int{0}
}

func (m *DepGraph) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepGraph.Unmarshal(m, b)
}
func (m *DepGraph) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepGraph.Marshal(b, m, deterministic)
}
func (m *DepGraph) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepGraph.Merge(m, src)
}
func (m *DepGraph) XXX_Size() int {
	return xxx_messageInfo_DepGraph.Size(m)
}
func (m *DepGraph) XXX_DiscardUnknown() {
	xxx_messageInfo_DepGraph.DiscardUnknown(m)
}

var xxx_messageInfo_DepGraph proto.InternalMessageInfo

func (m *DepGraph) GetBuildTarget() *chromiumos.BuildTarget {
	if m != nil {
		return m.BuildTarget
	}
	return nil
}

func (m *DepGraph) GetPackageDeps() []*PackageDepInfo {
	if m != nil {
		return m.PackageDeps
	}
	return nil
}

// Message describing a package and its dependencies.
type PackageDepInfo struct {
	PackageInfo *chromiumos.PackageInfo `protobuf:"bytes,1,opt,name=package_info,json=packageInfo,proto3" json:"package_info,omitempty"`
	// List of packages this package depends on.
	DependencyPackages []*chromiumos.PackageInfo `protobuf:"bytes,2,rep,name=dependency_packages,json=dependencyPackages,proto3" json:"dependency_packages,omitempty"`
	// List of source paths the package depends on.
	DependencySourcePaths []*SourcePath `protobuf:"bytes,3,rep,name=dependency_source_paths,json=dependencySourcePaths,proto3" json:"dependency_source_paths,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}      `json:"-"`
	XXX_unrecognized      []byte        `json:"-"`
	XXX_sizecache         int32         `json:"-"`
}

func (m *PackageDepInfo) Reset()         { *m = PackageDepInfo{} }
func (m *PackageDepInfo) String() string { return proto.CompactTextString(m) }
func (*PackageDepInfo) ProtoMessage()    {}
func (*PackageDepInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a5308b238ddba97, []int{1}
}

func (m *PackageDepInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageDepInfo.Unmarshal(m, b)
}
func (m *PackageDepInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageDepInfo.Marshal(b, m, deterministic)
}
func (m *PackageDepInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageDepInfo.Merge(m, src)
}
func (m *PackageDepInfo) XXX_Size() int {
	return xxx_messageInfo_PackageDepInfo.Size(m)
}
func (m *PackageDepInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageDepInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PackageDepInfo proto.InternalMessageInfo

func (m *PackageDepInfo) GetPackageInfo() *chromiumos.PackageInfo {
	if m != nil {
		return m.PackageInfo
	}
	return nil
}

func (m *PackageDepInfo) GetDependencyPackages() []*chromiumos.PackageInfo {
	if m != nil {
		return m.DependencyPackages
	}
	return nil
}

func (m *PackageDepInfo) GetDependencySourcePaths() []*SourcePath {
	if m != nil {
		return m.DependencySourcePaths
	}
	return nil
}

// Message describes a source path.
type SourcePath struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourcePath) Reset()         { *m = SourcePath{} }
func (m *SourcePath) String() string { return proto.CompactTextString(m) }
func (*SourcePath) ProtoMessage()    {}
func (*SourcePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a5308b238ddba97, []int{2}
}

func (m *SourcePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourcePath.Unmarshal(m, b)
}
func (m *SourcePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourcePath.Marshal(b, m, deterministic)
}
func (m *SourcePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourcePath.Merge(m, src)
}
func (m *SourcePath) XXX_Size() int {
	return xxx_messageInfo_SourcePath.Size(m)
}
func (m *SourcePath) XXX_DiscardUnknown() {
	xxx_messageInfo_SourcePath.DiscardUnknown(m)
}

var xxx_messageInfo_SourcePath proto.InternalMessageInfo

func (m *SourcePath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// Message for creating dependency graph json map.
// Example Json:
// {"build_target":{"name":"board"},"output_file":"/tmp/depgraph.json"}
type GetBuildDependencyGraphRequest struct {
	// The board whose dependency graph is being created.
	BuildTarget *chromiumos.BuildTarget `protobuf:"bytes,1,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	// The path where the dep graph json file is being saved to.
	OutputPath           string   `protobuf:"bytes,2,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBuildDependencyGraphRequest) Reset()         { *m = GetBuildDependencyGraphRequest{} }
func (m *GetBuildDependencyGraphRequest) String() string { return proto.CompactTextString(m) }
func (*GetBuildDependencyGraphRequest) ProtoMessage()    {}
func (*GetBuildDependencyGraphRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a5308b238ddba97, []int{3}
}

func (m *GetBuildDependencyGraphRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildDependencyGraphRequest.Unmarshal(m, b)
}
func (m *GetBuildDependencyGraphRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildDependencyGraphRequest.Marshal(b, m, deterministic)
}
func (m *GetBuildDependencyGraphRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildDependencyGraphRequest.Merge(m, src)
}
func (m *GetBuildDependencyGraphRequest) XXX_Size() int {
	return xxx_messageInfo_GetBuildDependencyGraphRequest.Size(m)
}
func (m *GetBuildDependencyGraphRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildDependencyGraphRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildDependencyGraphRequest proto.InternalMessageInfo

func (m *GetBuildDependencyGraphRequest) GetBuildTarget() *chromiumos.BuildTarget {
	if m != nil {
		return m.BuildTarget
	}
	return nil
}

func (m *GetBuildDependencyGraphRequest) GetOutputPath() string {
	if m != nil {
		return m.OutputPath
	}
	return ""
}

// Response from creating dependency graph json map.
type GetBuildDependencyGraphResponse struct {
	// The created dependency graph file
	BuildDependencyGraphFile string   `protobuf:"bytes,1,opt,name=build_dependency_graph_file,json=buildDependencyGraphFile,proto3" json:"build_dependency_graph_file,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *GetBuildDependencyGraphResponse) Reset()         { *m = GetBuildDependencyGraphResponse{} }
func (m *GetBuildDependencyGraphResponse) String() string { return proto.CompactTextString(m) }
func (*GetBuildDependencyGraphResponse) ProtoMessage()    {}
func (*GetBuildDependencyGraphResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7a5308b238ddba97, []int{4}
}

func (m *GetBuildDependencyGraphResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBuildDependencyGraphResponse.Unmarshal(m, b)
}
func (m *GetBuildDependencyGraphResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBuildDependencyGraphResponse.Marshal(b, m, deterministic)
}
func (m *GetBuildDependencyGraphResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBuildDependencyGraphResponse.Merge(m, src)
}
func (m *GetBuildDependencyGraphResponse) XXX_Size() int {
	return xxx_messageInfo_GetBuildDependencyGraphResponse.Size(m)
}
func (m *GetBuildDependencyGraphResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBuildDependencyGraphResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBuildDependencyGraphResponse proto.InternalMessageInfo

func (m *GetBuildDependencyGraphResponse) GetBuildDependencyGraphFile() string {
	if m != nil {
		return m.BuildDependencyGraphFile
	}
	return ""
}

func init() {
	proto.RegisterType((*DepGraph)(nil), "chromite.api.DepGraph")
	proto.RegisterType((*PackageDepInfo)(nil), "chromite.api.PackageDepInfo")
	proto.RegisterType((*SourcePath)(nil), "chromite.api.SourcePath")
	proto.RegisterType((*GetBuildDependencyGraphRequest)(nil), "chromite.api.GetBuildDependencyGraphRequest")
	proto.RegisterType((*GetBuildDependencyGraphResponse)(nil), "chromite.api.GetBuildDependencyGraphResponse")
}

func init() { proto.RegisterFile("chromite/api/depgraph.proto", fileDescriptor_7a5308b238ddba97) }

var fileDescriptor_7a5308b238ddba97 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x25, 0xad, 0x88, 0xde, 0x14, 0xc1, 0x11, 0x4d, 0x48, 0x8b, 0x2d, 0x59, 0x75, 0xa1, 0x29,
	0xd4, 0x9d, 0x20, 0x82, 0x14, 0xab, 0xbb, 0x92, 0xba, 0x8f, 0x93, 0xe4, 0xb6, 0x19, 0x6c, 0x32,
	0x63, 0x66, 0x52, 0x70, 0xe1, 0xda, 0x6f, 0xf1, 0x37, 0xde, 0xd7, 0xbc, 0xcd, 0xfb, 0x87, 0x47,
	0x66, 0xd2, 0xa6, 0x79, 0xb4, 0x8f, 0x07, 0x6f, 0xd7, 0x7b, 0xcf, 0x3d, 0xe7, 0x9e, 0x73, 0xa7,
	0x81, 0x61, 0x92, 0x95, 0x3c, 0x67, 0x0a, 0x67, 0x54, 0xb0, 0x59, 0x8a, 0x62, 0x5b, 0x52, 0x91,
	0x05, 0xa2, 0xe4, 0x8a, 0x93, 0xc1, 0x01, 0x0c, 0xa8, 0x60, 0xde, 0xa8, 0x33, 0x1a, 0x57, 0x6c,
	0x97, 0x46, 0x54, 0x30, 0x33, 0xeb, 0x39, 0x06, 0xad, 0x72, 0x2e, 0x67, 0x09, 0xcf, 0x73, 0x5e,
	0x18, 0xc0, 0xff, 0x67, 0xc1, 0xb3, 0x05, 0x8a, 0x65, 0xad, 0x4b, 0x3e, 0xc2, 0xc0, 0x10, 0x15,
	0x2d, 0xb7, 0xa8, 0x5c, 0x6b, 0x62, 0x4d, 0xed, 0xb9, 0x13, 0xb4, 0xe4, 0xe0, 0x4b, 0x8d, 0xff,
	0xd0, 0x70, 0x68, 0xc7, 0x6d, 0x41, 0x3e, 0xc3, 0x40, 0xd0, 0xe4, 0x17, 0xdd, 0x62, 0x94, 0xa2,
	0x90, 0x6e, 0x6f, 0xd2, 0x9f, 0xda, 0xf3, 0x51, 0x70, 0x6a, 0x32, 0x58, 0x99, 0x89, 0x05, 0x8a,
	0xef, 0xc5, 0x86, 0x87, 0xb6, 0x38, 0xd6, 0xd2, 0xbf, 0xb6, 0xe0, 0x45, 0x17, 0xaf, 0xfd, 0x1c,
	0x34, 0x59, 0xb1, 0xe1, 0xe7, 0xfc, 0x34, 0x8c, 0x8e, 0x9c, 0xe6, 0x7e, 0x83, 0x57, 0x29, 0x0a,
	0x2c, 0x52, 0x2c, 0x92, 0x3f, 0x51, 0x83, 0x1c, 0x6c, 0x5d, 0x94, 0x20, 0x2d, 0xa7, 0x69, 0x4b,
	0xb2, 0x02, 0xe7, 0x44, 0x49, 0xf2, 0xaa, 0x4c, 0x30, 0x12, 0x54, 0x65, 0xd2, 0xed, 0x6b, 0x35,
	0xb7, 0x1b, 0x72, 0xad, 0x27, 0x56, 0x54, 0x65, 0xe1, 0xeb, 0x96, 0xd8, 0x76, 0xa5, 0x3f, 0x01,
	0x68, 0x4b, 0x42, 0xe0, 0x49, 0xad, 0xa6, 0xd3, 0x3d, 0x0f, 0xf5, 0x6f, 0xff, 0x2f, 0xbc, 0x5d,
	0xa2, 0xd2, 0xc7, 0x5e, 0x1c, 0x25, 0xf4, 0x23, 0x85, 0xf8, 0xbb, 0x42, 0xa9, 0x1e, 0xf5, 0x56,
	0x63, 0xb0, 0x79, 0xa5, 0x44, 0xa5, 0x74, 0x0c, 0xb7, 0xa7, 0x17, 0x83, 0x69, 0xd5, 0x96, 0xfc,
	0x9f, 0x30, 0xbe, 0xb8, 0x5e, 0x0a, 0x5e, 0x48, 0x24, 0x9f, 0x60, 0x68, 0xf6, 0x9f, 0xdc, 0x46,
	0xff, 0x3b, 0xa3, 0x0d, 0xdb, 0x61, 0x13, 0xc6, 0x8d, 0xcf, 0x48, 0x7c, 0x65, 0x3b, 0x9c, 0xff,
	0xb7, 0xe0, 0x65, 0xdb, 0x5f, 0x63, 0xb9, 0x67, 0x09, 0x92, 0x3d, 0x38, 0x17, 0xf6, 0x92, 0x77,
	0xdd, 0x23, 0xdf, 0x7f, 0x1d, 0xef, 0xfd, 0x03, 0xa7, 0x4d, 0x18, 0x6f, 0x74, 0x75, 0xe3, 0xb9,
	0xf0, 0x26, 0xe6, 0xb4, 0x4c, 0xa3, 0xbb, 0xb1, 0xe2, 0xa7, 0xfa, 0x53, 0xf9, 0x70, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xbe, 0x9b, 0x84, 0xba, 0x8e, 0x03, 0x00, 0x00,
}
