// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromite/api/image.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	chromiumos "go.chromium.org/chromiumos/infra/proto/go/chromiumos"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The types of images that can be built.
type Image_Type int32

const (
	Image_IMAGE_TYPE_UNDEFINED Image_Type = 0
	Image_BASE                 Image_Type = 1
	Image_DEV                  Image_Type = 2
	Image_TEST                 Image_Type = 3
)

var Image_Type_name = map[int32]string{
	0: "IMAGE_TYPE_UNDEFINED",
	1: "BASE",
	2: "DEV",
	3: "TEST",
}

var Image_Type_value = map[string]int32{
	"IMAGE_TYPE_UNDEFINED": 0,
	"BASE":                 1,
	"DEV":                  2,
	"TEST":                 3,
}

func (x Image_Type) String() string {
	return proto.EnumName(Image_Type_name, int32(x))
}

func (Image_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_abef4ffabc69f3ed, []int{0, 0}
}

// Image argument - encapsulate data about an image.
type Image struct {
	// Path to the image file.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The image type.
	Type                 Image_Type `protobuf:"varint,2,opt,name=type,proto3,enum=chromite.api.Image_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_abef4ffabc69f3ed, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Image) GetType() Image_Type {
	if m != nil {
		return m.Type
	}
	return Image_IMAGE_TYPE_UNDEFINED
}

// The image test arguments.
type CreateImageRequest struct {
	// Required.
	// The build target whose image is being built.
	BuildTarget *chromiumos.BuildTarget `protobuf:"bytes,1,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	// The types of images to build, defaults to building base image.
	ImageTypes []Image_Type `protobuf:"varint,2,rep,packed,name=image_types,json=imageTypes,proto3,enum=chromite.api.Image_Type" json:"image_types,omitempty"`
	// Whether rootfs verification should be disabled (enabled by default).
	DisableRootfsVerification bool `protobuf:"varint,3,opt,name=disable_rootfs_verification,json=disableRootfsVerification,proto3" json:"disable_rootfs_verification,omitempty"`
	// The image version.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Disk layout option. See README.disk_layout and legacy_disk_layout.json in
	// src/scripts/build_library.
	DiskLayout string `protobuf:"bytes,5,opt,name=disk_layout,json=diskLayout,proto3" json:"disk_layout,omitempty"`
	// Used to set the LSB builder path key in /etc/lsb-release. See
	// chromite/scripts/cros_set_lsb_release.py.
	BuilderPath string `protobuf:"bytes,6,opt,name=builder_path,json=builderPath,proto3" json:"builder_path,omitempty"`
	// The chroot to use to execute the endpoint.
	Chroot               *chromiumos.Chroot `protobuf:"bytes,7,opt,name=chroot,proto3" json:"chroot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateImageRequest) Reset()         { *m = CreateImageRequest{} }
func (m *CreateImageRequest) String() string { return proto.CompactTextString(m) }
func (*CreateImageRequest) ProtoMessage()    {}
func (*CreateImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_abef4ffabc69f3ed, []int{1}
}

func (m *CreateImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateImageRequest.Unmarshal(m, b)
}
func (m *CreateImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateImageRequest.Marshal(b, m, deterministic)
}
func (m *CreateImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateImageRequest.Merge(m, src)
}
func (m *CreateImageRequest) XXX_Size() int {
	return xxx_messageInfo_CreateImageRequest.Size(m)
}
func (m *CreateImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateImageRequest proto.InternalMessageInfo

func (m *CreateImageRequest) GetBuildTarget() *chromiumos.BuildTarget {
	if m != nil {
		return m.BuildTarget
	}
	return nil
}

func (m *CreateImageRequest) GetImageTypes() []Image_Type {
	if m != nil {
		return m.ImageTypes
	}
	return nil
}

func (m *CreateImageRequest) GetDisableRootfsVerification() bool {
	if m != nil {
		return m.DisableRootfsVerification
	}
	return false
}

func (m *CreateImageRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CreateImageRequest) GetDiskLayout() string {
	if m != nil {
		return m.DiskLayout
	}
	return ""
}

func (m *CreateImageRequest) GetBuilderPath() string {
	if m != nil {
		return m.BuilderPath
	}
	return ""
}

func (m *CreateImageRequest) GetChroot() *chromiumos.Chroot {
	if m != nil {
		return m.Chroot
	}
	return nil
}

type CreateImageResult struct {
	// Whether it completed successfully.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Images that were built. Will contain no more than one per image type.
	Images []*Image `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	// Any packages that failed to build. Empty on success.
	FailedPackages       []*chromiumos.PackageInfo `protobuf:"bytes,3,rep,name=failed_packages,json=failedPackages,proto3" json:"failed_packages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *CreateImageResult) Reset()         { *m = CreateImageResult{} }
func (m *CreateImageResult) String() string { return proto.CompactTextString(m) }
func (*CreateImageResult) ProtoMessage()    {}
func (*CreateImageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_abef4ffabc69f3ed, []int{2}
}

func (m *CreateImageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateImageResult.Unmarshal(m, b)
}
func (m *CreateImageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateImageResult.Marshal(b, m, deterministic)
}
func (m *CreateImageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateImageResult.Merge(m, src)
}
func (m *CreateImageResult) XXX_Size() int {
	return xxx_messageInfo_CreateImageResult.Size(m)
}
func (m *CreateImageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateImageResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateImageResult proto.InternalMessageInfo

func (m *CreateImageResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateImageResult) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *CreateImageResult) GetFailedPackages() []*chromiumos.PackageInfo {
	if m != nil {
		return m.FailedPackages
	}
	return nil
}

// The image test arguments.
type TestImageRequest struct {
	// The image to be tested.
	// Image.path is required.
	Image *Image `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// The build target whose image is being tested.
	// BuildTarget.name is required.
	BuildTarget *chromiumos.BuildTarget `protobuf:"bytes,2,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	// Required.
	Result *TestImageRequest_Result `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// The chroot to use to execute the endpoint.
	Chroot               *chromiumos.Chroot `protobuf:"bytes,4,opt,name=chroot,proto3" json:"chroot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TestImageRequest) Reset()         { *m = TestImageRequest{} }
func (m *TestImageRequest) String() string { return proto.CompactTextString(m) }
func (*TestImageRequest) ProtoMessage()    {}
func (*TestImageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_abef4ffabc69f3ed, []int{3}
}

func (m *TestImageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestImageRequest.Unmarshal(m, b)
}
func (m *TestImageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestImageRequest.Marshal(b, m, deterministic)
}
func (m *TestImageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestImageRequest.Merge(m, src)
}
func (m *TestImageRequest) XXX_Size() int {
	return xxx_messageInfo_TestImageRequest.Size(m)
}
func (m *TestImageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestImageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestImageRequest proto.InternalMessageInfo

func (m *TestImageRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *TestImageRequest) GetBuildTarget() *chromiumos.BuildTarget {
	if m != nil {
		return m.BuildTarget
	}
	return nil
}

func (m *TestImageRequest) GetResult() *TestImageRequest_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *TestImageRequest) GetChroot() *chromiumos.Chroot {
	if m != nil {
		return m.Chroot
	}
	return nil
}

// Test results options specifications.
type TestImageRequest_Result struct {
	// Location where the test results should be written.
	Directory            string   `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestImageRequest_Result) Reset()         { *m = TestImageRequest_Result{} }
func (m *TestImageRequest_Result) String() string { return proto.CompactTextString(m) }
func (*TestImageRequest_Result) ProtoMessage()    {}
func (*TestImageRequest_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_abef4ffabc69f3ed, []int{3, 0}
}

func (m *TestImageRequest_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestImageRequest_Result.Unmarshal(m, b)
}
func (m *TestImageRequest_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestImageRequest_Result.Marshal(b, m, deterministic)
}
func (m *TestImageRequest_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestImageRequest_Result.Merge(m, src)
}
func (m *TestImageRequest_Result) XXX_Size() int {
	return xxx_messageInfo_TestImageRequest_Result.Size(m)
}
func (m *TestImageRequest_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_TestImageRequest_Result.DiscardUnknown(m)
}

var xxx_messageInfo_TestImageRequest_Result proto.InternalMessageInfo

func (m *TestImageRequest_Result) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

type TestImageResult struct {
	// Whether all tests passed.
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestImageResult) Reset()         { *m = TestImageResult{} }
func (m *TestImageResult) String() string { return proto.CompactTextString(m) }
func (*TestImageResult) ProtoMessage()    {}
func (*TestImageResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_abef4ffabc69f3ed, []int{4}
}

func (m *TestImageResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestImageResult.Unmarshal(m, b)
}
func (m *TestImageResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestImageResult.Marshal(b, m, deterministic)
}
func (m *TestImageResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestImageResult.Merge(m, src)
}
func (m *TestImageResult) XXX_Size() int {
	return xxx_messageInfo_TestImageResult.Size(m)
}
func (m *TestImageResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TestImageResult.DiscardUnknown(m)
}

var xxx_messageInfo_TestImageResult proto.InternalMessageInfo

func (m *TestImageResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterEnum("chromite.api.Image_Type", Image_Type_name, Image_Type_value)
	proto.RegisterType((*Image)(nil), "chromite.api.Image")
	proto.RegisterType((*CreateImageRequest)(nil), "chromite.api.CreateImageRequest")
	proto.RegisterType((*CreateImageResult)(nil), "chromite.api.CreateImageResult")
	proto.RegisterType((*TestImageRequest)(nil), "chromite.api.TestImageRequest")
	proto.RegisterType((*TestImageRequest_Result)(nil), "chromite.api.TestImageRequest.Result")
	proto.RegisterType((*TestImageResult)(nil), "chromite.api.TestImageResult")
}

func init() { proto.RegisterFile("chromite/api/image.proto", fileDescriptor_abef4ffabc69f3ed) }

var fileDescriptor_abef4ffabc69f3ed = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x6d, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x89, 0xeb, 0xb6, 0xe3, 0xd2, 0x86, 0x05, 0xa9, 0xc6, 0x14, 0x1a, 0x22, 0x81, 0x0a,
	0x45, 0xb6, 0x14, 0x24, 0x04, 0x48, 0x45, 0xf4, 0xc3, 0xa0, 0x08, 0xa8, 0x2a, 0x37, 0x54, 0x82,
	0x3f, 0xd6, 0xc6, 0xd9, 0xa4, 0xab, 0x26, 0x59, 0xb3, 0xbb, 0xa9, 0x94, 0x1b, 0xf0, 0x83, 0x23,
	0x70, 0x09, 0xae, 0xc0, 0x1d, 0x38, 0x06, 0x77, 0x40, 0x3b, 0x76, 0xa9, 0x43, 0x4b, 0x10, 0xff,
	0x3c, 0xf3, 0xde, 0xec, 0xcc, 0xbc, 0xe7, 0x5d, 0xf0, 0xd2, 0x63, 0x29, 0x86, 0x5c, 0xb3, 0x90,
	0x66, 0x3c, 0xe4, 0x43, 0xda, 0x67, 0x41, 0x26, 0x85, 0x16, 0x64, 0xe9, 0x0c, 0x09, 0x68, 0xc6,
	0xfd, 0xb5, 0x29, 0x5e, 0x67, 0xcc, 0x07, 0xdd, 0x84, 0x66, 0x3c, 0xe7, 0xfa, 0xab, 0x39, 0x3a,
	0x1e, 0x0a, 0x15, 0xa6, 0x62, 0x38, 0x14, 0xa3, 0x1c, 0x68, 0x7c, 0xb6, 0x60, 0xae, 0x65, 0x0e,
	0x25, 0x04, 0xec, 0x8c, 0xea, 0x63, 0xcf, 0xaa, 0x5b, 0x1b, 0x8b, 0x31, 0x7e, 0x93, 0x47, 0x60,
	0xeb, 0x49, 0xc6, 0xbc, 0x4a, 0xdd, 0xda, 0x58, 0x6e, 0x7a, 0x41, 0xb9, 0x63, 0x80, 0x65, 0x41,
	0x7b, 0x92, 0xb1, 0x18, 0x59, 0x8d, 0x2d, 0xb0, 0x4d, 0x44, 0x3c, 0xb8, 0xd1, 0x7a, 0xb7, 0xfd,
	0x3a, 0x4a, 0xda, 0x1f, 0x0e, 0xa2, 0xe4, 0xfd, 0xfe, 0x5e, 0xf4, 0xaa, 0xb5, 0x1f, 0xed, 0xd5,
	0xae, 0x90, 0x05, 0xb0, 0x77, 0xb6, 0x0f, 0xa3, 0x9a, 0x45, 0xe6, 0xa1, 0xba, 0x17, 0x1d, 0xd5,
	0x2a, 0x26, 0xd5, 0x8e, 0x0e, 0xdb, 0xb5, 0x6a, 0xe3, 0x47, 0x05, 0xc8, 0xae, 0x64, 0x54, 0x33,
	0x3c, 0x39, 0x66, 0x9f, 0xc6, 0x4c, 0x69, 0xf2, 0x1c, 0x96, 0xf2, 0x6d, 0x34, 0x95, 0x7d, 0xa6,
	0x71, 0x3e, 0xb7, 0xb9, 0x1a, 0x9c, 0x6f, 0x14, 0xec, 0x18, 0xbc, 0x8d, 0x70, 0xec, 0x76, 0xce,
	0x03, 0xf2, 0x0c, 0x5c, 0x54, 0x2c, 0x31, 0xf3, 0x29, 0xaf, 0x52, 0xaf, 0xce, 0x5c, 0x03, 0x90,
	0x6c, 0x3e, 0x15, 0x79, 0x01, 0xb7, 0xba, 0x5c, 0xd1, 0xce, 0x80, 0x25, 0x52, 0x08, 0xdd, 0x53,
	0xc9, 0x29, 0x93, 0xbc, 0xc7, 0x53, 0xaa, 0xb9, 0x18, 0x79, 0xd5, 0xba, 0xb5, 0xb1, 0x10, 0xdf,
	0x2c, 0x28, 0x31, 0x32, 0x8e, 0x4a, 0x04, 0xe2, 0xc1, 0xfc, 0x29, 0x93, 0xca, 0x70, 0x6d, 0x54,
	0xf4, 0x2c, 0x24, 0xeb, 0xe0, 0x76, 0xb9, 0x3a, 0x49, 0x06, 0x74, 0x22, 0xc6, 0xda, 0x9b, 0x43,
	0x14, 0x4c, 0xea, 0x2d, 0x66, 0xc8, 0xdd, 0x62, 0x63, 0x26, 0x13, 0x74, 0xc4, 0x41, 0x86, 0x5b,
	0xe4, 0x0e, 0x8c, 0x31, 0x0f, 0xc1, 0x31, 0x4b, 0x08, 0xed, 0xcd, 0xa3, 0x1c, 0xa4, 0x2c, 0xc7,
	0x2e, 0x22, 0x71, 0xc1, 0x68, 0x7c, 0xb5, 0xe0, 0xda, 0x94, 0xae, 0x6a, 0x3c, 0xd0, 0x66, 0x3e,
	0x35, 0x4e, 0x53, 0xa6, 0x14, 0x2a, 0xba, 0x10, 0x9f, 0x85, 0x64, 0x13, 0x1c, 0xd4, 0x21, 0xd7,
	0xcb, 0x6d, 0x5e, 0xbf, 0x44, 0xaf, 0xb8, 0xa0, 0x90, 0x97, 0xb0, 0xd2, 0xa3, 0x7c, 0xc0, 0xba,
	0x49, 0x46, 0xd3, 0x13, 0xac, 0xaa, 0x62, 0xd5, 0x94, 0x41, 0x07, 0x39, 0xd6, 0x1a, 0xf5, 0x44,
	0xbc, 0x9c, 0xf3, 0x8b, 0x94, 0x6a, 0x7c, 0xa9, 0x40, 0xad, 0xcd, 0x94, 0x9e, 0x32, 0xfd, 0x01,
	0xcc, 0x61, 0x83, 0xc2, 0xed, 0x4b, 0x47, 0xc8, 0x19, 0x17, 0xfe, 0x8f, 0xca, 0x7f, 0xfc, 0x1f,
	0x5b, 0xe0, 0x48, 0x94, 0x03, 0xfd, 0x74, 0x9b, 0xf7, 0xa6, 0xfb, 0xfc, 0x39, 0x56, 0x90, 0x6b,
	0x17, 0x17, 0x45, 0x25, 0x17, 0xec, 0x7f, 0xb9, 0xe0, 0xdf, 0x07, 0xa7, 0x50, 0x7e, 0x0d, 0x16,
	0xbb, 0x5c, 0xb2, 0x54, 0x0b, 0x39, 0x29, 0x6e, 0xdb, 0x79, 0xa2, 0xb1, 0x09, 0x2b, 0xa5, 0xb6,
	0xb3, 0xad, 0x6a, 0x7e, 0xb3, 0x60, 0x09, 0x99, 0x87, 0x4c, 0x9e, 0xf2, 0x94, 0x91, 0x37, 0xe0,
	0xe4, 0x56, 0x93, 0xfa, 0xf4, 0x2a, 0x17, 0x2f, 0x96, 0xbf, 0x3e, 0x83, 0x81, 0x7d, 0x23, 0xb0,
	0xcd, 0x28, 0xe4, 0xce, 0x6c, 0x55, 0xfc, 0xdb, 0x7f, 0xc5, 0xcd, 0x31, 0xfe, 0xd5, 0xef, 0x3f,
	0xfd, 0xc5, 0xc2, 0xcf, 0x9a, 0xb5, 0xf3, 0xf4, 0xe3, 0x93, 0xbe, 0xf8, 0x2d, 0x54, 0x20, 0x64,
	0x3f, 0x2c, 0x3d, 0x4e, 0x7c, 0xd4, 0x93, 0x34, 0xc4, 0xb7, 0x29, 0xec, 0x8b, 0xb0, 0xfc, 0xa8,
	0x75, 0x1c, 0x4c, 0x3f, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x55, 0xbd, 0x83, 0x13, 0x05,
	0x00, 0x00,
}
