// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chromite/api/test.proto

package chromite_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "go.chromium.org/chromiumos/infra/proto/go/chromite/api"
	chromiumos "go.chromium.org/chromiumos/infra/proto/go/chromiumos"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Run the debug_info_test script.
type DebugInfoTestRequest struct {
	// The sysroot to tests.
	Sysroot *Sysroot `protobuf:"bytes,1,opt,name=sysroot,proto3" json:"sysroot,omitempty"`
	// The chroot to use to execute the endpoint.
	Chroot               *chromiumos.Chroot `protobuf:"bytes,2,opt,name=chroot,proto3" json:"chroot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DebugInfoTestRequest) Reset()         { *m = DebugInfoTestRequest{} }
func (m *DebugInfoTestRequest) String() string { return proto.CompactTextString(m) }
func (*DebugInfoTestRequest) ProtoMessage()    {}
func (*DebugInfoTestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5c91b4ac6233d9e, []int{0}
}

func (m *DebugInfoTestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebugInfoTestRequest.Unmarshal(m, b)
}
func (m *DebugInfoTestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebugInfoTestRequest.Marshal(b, m, deterministic)
}
func (m *DebugInfoTestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebugInfoTestRequest.Merge(m, src)
}
func (m *DebugInfoTestRequest) XXX_Size() int {
	return xxx_messageInfo_DebugInfoTestRequest.Size(m)
}
func (m *DebugInfoTestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DebugInfoTestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DebugInfoTestRequest proto.InternalMessageInfo

func (m *DebugInfoTestRequest) GetSysroot() *Sysroot {
	if m != nil {
		return m.Sysroot
	}
	return nil
}

func (m *DebugInfoTestRequest) GetChroot() *chromiumos.Chroot {
	if m != nil {
		return m.Chroot
	}
	return nil
}

type BuildTargetUnitTestRequest struct {
	// The build target being tested.
	BuildTarget *chromiumos.BuildTarget `protobuf:"bytes,1,opt,name=build_target,json=buildTarget,proto3" json:"build_target,omitempty"`
	// The path where the result tarball should be saved.
	ResultPath string `protobuf:"bytes,2,opt,name=result_path,json=resultPath,proto3" json:"result_path,omitempty"`
	// The chroot containing the sysroot.
	Chroot               *chromiumos.Chroot `protobuf:"bytes,3,opt,name=chroot,proto3" json:"chroot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BuildTargetUnitTestRequest) Reset()         { *m = BuildTargetUnitTestRequest{} }
func (m *BuildTargetUnitTestRequest) String() string { return proto.CompactTextString(m) }
func (*BuildTargetUnitTestRequest) ProtoMessage()    {}
func (*BuildTargetUnitTestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5c91b4ac6233d9e, []int{1}
}

func (m *BuildTargetUnitTestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTargetUnitTestRequest.Unmarshal(m, b)
}
func (m *BuildTargetUnitTestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTargetUnitTestRequest.Marshal(b, m, deterministic)
}
func (m *BuildTargetUnitTestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTargetUnitTestRequest.Merge(m, src)
}
func (m *BuildTargetUnitTestRequest) XXX_Size() int {
	return xxx_messageInfo_BuildTargetUnitTestRequest.Size(m)
}
func (m *BuildTargetUnitTestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTargetUnitTestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTargetUnitTestRequest proto.InternalMessageInfo

func (m *BuildTargetUnitTestRequest) GetBuildTarget() *chromiumos.BuildTarget {
	if m != nil {
		return m.BuildTarget
	}
	return nil
}

func (m *BuildTargetUnitTestRequest) GetResultPath() string {
	if m != nil {
		return m.ResultPath
	}
	return ""
}

func (m *BuildTargetUnitTestRequest) GetChroot() *chromiumos.Chroot {
	if m != nil {
		return m.Chroot
	}
	return nil
}

type BuildTargetUnitTestResponse struct {
	// The unittest tarball that was created.
	TarballPath string `protobuf:"bytes,1,opt,name=tarball_path,json=tarballPath,proto3" json:"tarball_path,omitempty"`
	// The list of packages that failed.
	FailedPackages       []*chromiumos.PackageInfo `protobuf:"bytes,2,rep,name=failed_packages,json=failedPackages,proto3" json:"failed_packages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BuildTargetUnitTestResponse) Reset()         { *m = BuildTargetUnitTestResponse{} }
func (m *BuildTargetUnitTestResponse) String() string { return proto.CompactTextString(m) }
func (*BuildTargetUnitTestResponse) ProtoMessage()    {}
func (*BuildTargetUnitTestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5c91b4ac6233d9e, []int{2}
}

func (m *BuildTargetUnitTestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildTargetUnitTestResponse.Unmarshal(m, b)
}
func (m *BuildTargetUnitTestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildTargetUnitTestResponse.Marshal(b, m, deterministic)
}
func (m *BuildTargetUnitTestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildTargetUnitTestResponse.Merge(m, src)
}
func (m *BuildTargetUnitTestResponse) XXX_Size() int {
	return xxx_messageInfo_BuildTargetUnitTestResponse.Size(m)
}
func (m *BuildTargetUnitTestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildTargetUnitTestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildTargetUnitTestResponse proto.InternalMessageInfo

func (m *BuildTargetUnitTestResponse) GetTarballPath() string {
	if m != nil {
		return m.TarballPath
	}
	return ""
}

func (m *BuildTargetUnitTestResponse) GetFailedPackages() []*chromiumos.PackageInfo {
	if m != nil {
		return m.FailedPackages
	}
	return nil
}

func init() {
	proto.RegisterType((*DebugInfoTestRequest)(nil), "chromite.api.DebugInfoTestRequest")
	proto.RegisterType((*BuildTargetUnitTestRequest)(nil), "chromite.api.BuildTargetUnitTestRequest")
	proto.RegisterType((*BuildTargetUnitTestResponse)(nil), "chromite.api.BuildTargetUnitTestResponse")
}

func init() { proto.RegisterFile("chromite/api/test.proto", fileDescriptor_f5c91b4ac6233d9e) }

var fileDescriptor_f5c91b4ac6233d9e = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcb, 0x8e, 0xda, 0x30,
	0x14, 0x55, 0x42, 0x45, 0x5b, 0x27, 0x6d, 0x91, 0xfb, 0x00, 0x99, 0x4a, 0xa5, 0x59, 0xd1, 0x2e,
	0x1c, 0x89, 0xee, 0xba, 0xaa, 0xfa, 0x58, 0x54, 0xdd, 0xa0, 0x40, 0xd7, 0xc8, 0x09, 0x26, 0x58,
	0x93, 0xc4, 0x1e, 0xdb, 0x19, 0x89, 0xed, 0xfc, 0xcb, 0xfc, 0x08, 0xdf, 0x31, 0xbf, 0xc0, 0x3f,
	0x8c, 0x62, 0x1b, 0x91, 0x8c, 0x18, 0xcd, 0x2c, 0xef, 0x3d, 0x27, 0xf7, 0x9c, 0x9b, 0x73, 0x0d,
	0x86, 0xd9, 0x56, 0xf2, 0x92, 0x69, 0x1a, 0x13, 0xc1, 0x62, 0x4d, 0x95, 0xc6, 0x42, 0x72, 0xcd,
	0x61, 0x78, 0x04, 0x30, 0x11, 0x0c, 0x7d, 0xec, 0xd0, 0xd2, 0x9a, 0x15, 0xeb, 0x15, 0x11, 0xcc,
	0x72, 0x11, 0xea, 0xa0, 0x6a, 0xa7, 0x24, 0xe7, 0x6e, 0x0e, 0x72, 0x02, 0x75, 0xc9, 0x55, 0x9c,
	0xf1, 0xb2, 0xe4, 0x95, 0x03, 0xc6, 0x39, 0xe7, 0x79, 0x41, 0x63, 0x53, 0xa5, 0xf5, 0x26, 0xa6,
	0xa5, 0xd0, 0x3b, 0x0b, 0x46, 0x0a, 0xbc, 0xfb, 0x4d, 0xd3, 0x3a, 0xff, 0x5b, 0x6d, 0xf8, 0x92,
	0x2a, 0x9d, 0xd0, 0xcb, 0x9a, 0x2a, 0x0d, 0x63, 0xf0, 0xdc, 0x8d, 0x1f, 0x79, 0x13, 0x6f, 0x1a,
	0xcc, 0xde, 0xe3, 0xb6, 0x4f, 0xbc, 0xb0, 0x60, 0x72, 0x64, 0xc1, 0xaf, 0xa0, 0xdf, 0x10, 0xb8,
	0x1e, 0xf9, 0x86, 0x0f, 0xf1, 0xc9, 0x0f, 0xfe, 0x65, 0x90, 0xc4, 0x31, 0xa2, 0x1b, 0x0f, 0xa0,
	0x9f, 0xcd, 0x6a, 0x4b, 0x22, 0x73, 0xaa, 0xff, 0x57, 0x4c, 0xb7, 0xb5, 0xbf, 0x83, 0xd0, 0x2e,
	0xae, 0x0d, 0xec, 0x0c, 0x0c, 0xdb, 0x03, 0x5b, 0x5f, 0x27, 0x41, 0x7a, 0x2a, 0xe0, 0x27, 0x10,
	0x48, 0xaa, 0xea, 0x42, 0xaf, 0x04, 0xd1, 0x5b, 0xe3, 0xe5, 0x65, 0x02, 0x6c, 0x6b, 0x4e, 0xf4,
	0xb6, 0xe5, 0xb3, 0xf7, 0xa8, 0xcf, 0x6b, 0x0f, 0x8c, 0xcf, 0xfa, 0x54, 0x82, 0x57, 0x8a, 0xc2,
	0xcf, 0x20, 0xd4, 0x44, 0xa6, 0xa4, 0x28, 0xac, 0x9a, 0x67, 0xd4, 0x02, 0xd7, 0x33, 0x72, 0x3f,
	0xc0, 0x9b, 0x0d, 0x61, 0x05, 0x5d, 0xaf, 0x04, 0xc9, 0x2e, 0x48, 0x4e, 0xd5, 0xc8, 0x9f, 0xf4,
	0xee, 0xaf, 0x33, 0xb7, 0x58, 0x13, 0x42, 0xf2, 0xda, 0xf2, 0x5d, 0x4b, 0xcd, 0x6e, 0x3d, 0x10,
	0x34, 0xaa, 0x0b, 0x2a, 0xaf, 0x58, 0x46, 0xe1, 0x3f, 0xf0, 0xaa, 0x93, 0x18, 0x8c, 0xba, 0xc9,
	0x9c, 0x8b, 0x13, 0x7d, 0xc0, 0xf6, 0x08, 0xf0, 0xf1, 0x08, 0xf0, 0x9f, 0xe6, 0x08, 0xa0, 0x04,
	0x6f, 0xcf, 0x2c, 0x08, 0xa7, 0xdd, 0x91, 0x0f, 0x67, 0x85, 0xbe, 0x3c, 0x81, 0x69, 0xff, 0x56,
	0xd4, 0xdf, 0x1f, 0x90, 0x3f, 0xf0, 0x51, 0xb8, 0x3f, 0xa0, 0x17, 0xe0, 0x59, 0xf3, 0x04, 0x06,
	0x5e, 0xda, 0x37, 0x8e, 0xbe, 0xdd, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xc4, 0xde, 0xda, 0x20,
	0x03, 0x00, 0x00,
}
